/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */

package bgc.gui.proy.nuevo.especial;

import bgc.bd.GestorBD;
import bgc.gui.VContenedor;
import bgc.gui.inicio.VInicio;
import bgc.gui.proy.nuevo.VNuevoProy1;
import bgc.negocio.proyecto.GuardarProy;
import bgc.negocio.proyecto.Proyecto;
import bgc.negocio.proyecto.ProyectoAuto;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;

/**
 * Panel Especial
 * @author Campus-Telematika S.L.
 */
public class PanelEspecial extends JPanel {
    
    /**
     * Ventana padre
     */
    VNuevoProy2Esp padre;
    /**
     * Proyecto especial
     */
    Proyecto proy;
    /**
     * Creates new form PanelEspecial
     * @param padre Ventana padre
     * @param proy Proyecto Especial
     */
    public PanelEspecial(VNuevoProy2Esp padre,Proyecto proy) {
        initComponents();
        this.padre=padre;
        this.proy=proy;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textoAsunto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textoHTML = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 228, 198));
        setOpaque(false);
        jLabel1.setBackground(new java.awt.Color(216, 228, 198));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setText("Evento especial:");

        jRadioButton1.setBackground(new java.awt.Color(216, 228, 198));
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 12));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Cumplea\u00f1os");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton1.setOpaque(false);

        jButton2.setBackground(new java.awt.Color(240, 240, 240));
        jButton2.setFont(new java.awt.Font("Arial", 0, 12));
        jButton2.setText("Anterior");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(240, 240, 240));
        jButton3.setFont(new java.awt.Font("Arial", 0, 12));
        jButton3.setText("Finalizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(216, 228, 198));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel2.setText("Asunto mailing");

        textoAsunto.setBackground(new java.awt.Color(216, 228, 198));
        textoAsunto.setFont(new java.awt.Font("Arial", 0, 12));
        textoAsunto.setText("!Feliz Cumplea\u00f1os\u00a1");
        textoAsunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoAsuntoMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(216, 228, 198));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel3.setText("Elegir dise\u00f1o");

        jButton1.setBackground(new java.awt.Color(240, 240, 240));
        jButton1.setFont(new java.awt.Font("Arial", 0, 12));
        jButton1.setText("Elegir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textoHTML.setBackground(new java.awt.Color(216, 228, 198));
        textoHTML.setFont(new java.awt.Font("Arial", 1, 12));
        textoHTML.setForeground(new java.awt.Color(0, 0, 204));
        textoHTML.setText("Elija dise\u00f1o");
        textoHTML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoHTMLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoHTMLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoHTMLMouseExited(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jRadioButton1)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel2)
                                    .add(jLabel3))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(textoHTML, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jButton1))
                                    .add(textoAsunto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(284, Short.MAX_VALUE)
                        .add(jButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jRadioButton1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(textoAsunto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jButton1)
                    .add(textoHTML, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton3)
                    .add(jButton2))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Cambia el cursor a normal
     * @param evt Evento
     */
    private void textoHTMLMouseExited(MouseEvent evt) {//GEN-FIRST:event_textoHTMLMouseExited
// TODO add your handling code here:
        textoHTML.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_textoHTMLMouseExited
    
    /**
     * Cambia el cursor a Mano
     * @param evt Evento
     */
    private void textoHTMLMouseEntered(MouseEvent evt) {//GEN-FIRST:event_textoHTMLMouseEntered
// TODO add your handling code here:
        textoHTML.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_textoHTMLMouseEntered
    
    /**
     * Abre el HTML
     * @param evt Evento
     */
    private void textoHTMLMouseClicked(MouseEvent evt) {//GEN-FIRST:event_textoHTMLMouseClicked
// TODO add your handling code here:
        if (!textoHTML.getText().equals("Elija un diseño"))
        {
        Runtime rtt=Runtime.getRuntime();
        try {
            rtt.exec("cmd /c start iexplore \""+proy.getHtml()+"\"");;
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        }
    }//GEN-LAST:event_textoHTMLMouseClicked
    
    /**
     * Limpia el campo textoAsunto
     * @param evt Evento
     */
    private void textoAsuntoMouseClicked(MouseEvent evt) {//GEN-FIRST:event_textoAsuntoMouseClicked
// TODO add your handling code here:
        textoAsunto.setText("");
    }//GEN-LAST:event_textoAsuntoMouseClicked
    
    /**
     * Abre el Html
     * @param evt Evento
     */
    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Seleccionar HTML");
        FileFilter filtroObj = new FileFilter() {
            public boolean accept(File f) {
                return f.getName().toLowerCase().endsWith(".html") || f.isDirectory()||f.getName().toLowerCase().endsWith(".htm");
            }
            public String getDescription() {
                return "Paginas Web";
            }
        };
        chooser.setFileFilter(filtroObj);
        
        chooser.setCurrentDirectory(new File("C:\\Archivos de programa\\Campus-Telematika\\Hermes"));
        int resultado = chooser.showOpenDialog(this.getParent());
        if (resultado == JFileChooser.APPROVE_OPTION){
            File ficheroSeleccionado = chooser.getSelectedFile();
            textoHTML.setText(ficheroSeleccionado.getName());
            proy.setHtml(ficheroSeleccionado.getAbsolutePath());
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * 
     * @param evt 
     */
    private void jButton3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
      
        if (this.textoAsunto.getText().equals(""))
        {
            JOptionPane mensaje = new JOptionPane();
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            mensaje.setLocation(screenSize.width/2-mensaje.getSize().width/2, screenSize.height/2-mensaje.getSize().height/2);
            mensaje.showMessageDialog(this,"¡Debe rellenar el asunto del e-mail!","Aviso",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if ( textoHTML.getText().equals("Elija diseño") ) {
                JOptionPane.showMessageDialog(this,"¡Debe seleccionar el documento HTML!","Aviso",JOptionPane.WARNING_MESSAGE);
                return;
            }
        
            proy.setTipo(Proyecto.ESPECIAL);
            ((ProyectoAuto)proy).setTipoEnv(ProyectoAuto.ESPECIAL);
            proy.setAsunto(textoAsunto.getText());
             proy.setSql("Select * from Clientes");
            GuardarProy salida = new GuardarProy();
            File fich = new File(proy.getNombre());
            try {
                proy.setRuta(proy.getNombre());
                fich.mkdir();
                salida.abrir(proy.getNombre()+System.getProperty("file.separator")+proy.getNombre()+".bgc");
                GestorBD gbd=new GestorBD();
                gbd.abrirBD();
                gbd.insertarProyectoAuto(proy.getNombre()+System.getProperty("file.separator")+proy.getNombre()+".bgc");
                gbd.cerrarBD();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            salida.escribir(proy);
            salida.cerrar();
            ((VContenedor) (this.getParent().getParent().getParent().getParent().getParent().getParent().getParent().getParent().getParent().getParent())).gestorAuto.iniciarProyectosAuto();
            VInicio v = new VInicio();
            this.padre.getParent().add(v);
            this.padre.dispose();
           
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2);
            
            v.show();
            
            
    }//GEN-LAST:event_jButton3ActionPerformed
        
    /**
     * Cierra la ventana
     * @param evt 
     */
    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        VNuevoProy1 v = new VNuevoProy1(proy);
        this.padre.getParent().add(v);
        this.padre.dispose();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2);
        v.show();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField textoAsunto;
    private javax.swing.JLabel textoHTML;
    // End of variables declaration//GEN-END:variables
    
    }
