/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */

package bgc.gui.config;

import bgc.asistente.VPaso1;
import bgc.negocio.DatosNegocio;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.border.LineBorder;
import javax.swing.border.TitledBorder;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;
import javax.swing.text.Style;
import javax.swing.text.StyledDocument;
import javax.swing.text.rtf.RTFEditorKit;

/**
 * Clase PanelOpciones donde se cargan las opciones de configuración
 * @author Campu-Telematika S.L.
 */
public class PanelOpciones extends javax.swing.JPanel {
    
    /** Creates new form PanelOpciones */
    public PanelOpciones() {
        initComponents();
        jTabbedPane1.setTitleAt(0,"Proteccion de datos");
        jTabbedPane1.setTitleAt(1,"Datos del comercio");
        jTabbedPane1.setTitleAt(2,"Acerca de ...");
        texto.setEditable(false);
        jTextArea2.setEditable(false);
        textoNombre.setEditable(false);
        textoEmail.setEditable(false);
        textoCIF.setEditable(false);
        ((TitledBorder)panelDatos.getBorder()).setBorder(new LineBorder(Color.ORANGE,1));
        DatosNegocio datos=new DatosNegocio();
        try {
            
            datos.leerDatos();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
        textoEmail.setText(datos.getEmail());
        textoNombre.setText(datos.getNombreComercio());
        textoCIF.setText(datos.getCif());
        
        editor=new RTFEditorKit();
        editor.install(texto);
        try{
             FileInputStream io=new FileInputStream("c:\\Archivos de Programa\\Campus-Telematika\\Hermes\\ayuda\\accionlopd.rtf");
            editor.read(io,texto.getDocument(),0);
            
           } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (BadLocationException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelAPD = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextPane();
        panelDatos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textoCIF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textoEmail = new javax.swing.JTextField();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        panelBD = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFocusTraversalPolicyProvider(true);
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        panelAPD.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hermes/imagenes/configuracion/img_importante.png")));
        jLabel1.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Pagina web de alta de ficheros en la Agencia de Protecci\u00f3n de Datos");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        texto.setEditable(false);
        texto.setContentType("text/rtf");
        texto.setRequestFocusEnabled(false);
        texto.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(texto);

        org.jdesktop.layout.GroupLayout panelAPDLayout = new org.jdesktop.layout.GroupLayout(panelAPD);
        panelAPD.setLayout(panelAPDLayout);
        panelAPDLayout.setHorizontalGroup(
            panelAPDLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelAPDLayout.createSequentialGroup()
                .add(253, 253, 253)
                .add(jLabel5)
                .addContainerGap(615, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panelAPDLayout.createSequentialGroup()
                .addContainerGap(682, Short.MAX_VALUE)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 257, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(317, 317, 317))
            .add(panelAPDLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1236, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAPDLayout.setVerticalGroup(
            panelAPDLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelAPDLayout.createSequentialGroup()
                .add(jLabel1)
                .add(11, 11, 11)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5)
                .addContainerGap())
        );
        jTabbedPane1.addTab("tab2", panelAPD);

        panelDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos actuales", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 102, 0)));
        jLabel3.setText("Nombre Comercio");

        textoCIF.setBackground(new java.awt.Color(230, 237, 220));

        jLabel2.setText("CIF");

        textoNombre.setBackground(new java.awt.Color(230, 237, 220));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Email");

        textoEmail.setBackground(new java.awt.Color(230, 237, 220));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 12));
        jTextArea2.setRows(5);
        jTextArea2.setText("En esta opci\u00f3n puede volver a ejecutar el asistente para la configuraci\u00f3n de la base de datos.\n");
        jTextArea2.setOpaque(false);

        jButton1.setText("Asistente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setForeground(new java.awt.Color(219, 129, 0));
        jLabel6.setText("*  Aviso:  La ejecuci\u00f3n del asistente conlleva la perdida de los datos opcionales configurados anteriormente");

        org.jdesktop.layout.GroupLayout panelDatosLayout = new org.jdesktop.layout.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelDatosLayout.createSequentialGroup()
                        .add(jTextArea2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 538, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1))
                    .add(panelDatosLayout.createSequentialGroup()
                        .add(panelDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jLabel2)
                            .add(jLabel4))
                        .add(37, 37, 37)
                        .add(panelDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(textoNombre, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .add(textoCIF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .add(textoEmail)))
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 647, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(583, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(textoNombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(25, 25, 25)
                .add(panelDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textoCIF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(21, 21, 21)
                .add(panelDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textoEmail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .add(40, 40, 40)
                .add(panelDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextArea2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1))
                .add(16, 16, 16)
                .add(jLabel6)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jTabbedPane1.addTab("tab1", panelDatos);

        panelBD.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel7.setText("Desarrollado por:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel8.setText("Campus-Telematika  S.L.");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel9.setText("Aplicaci\u00f3n:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel10.setText("Hermes Marketing de fidelizaci\u00f3n");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel11.setText("Versi\u00f3n:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel12.setText("1.0 b");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel13.setText("Pagina web");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel14.setText("www.campus-telematika.com/hermes");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hermes/imagenes/config/company_logo.png")));

        org.jdesktop.layout.GroupLayout panelBDLayout = new org.jdesktop.layout.GroupLayout(panelBD);
        panelBD.setLayout(panelBDLayout);
        panelBDLayout.setHorizontalGroup(
            panelBDLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelBDLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelBDLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelBDLayout.createSequentialGroup()
                        .add(panelBDLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel9)
                            .add(jLabel11))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 43, Short.MAX_VALUE)
                        .add(panelBDLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 202, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 202, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(942, 942, 942))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelBDLayout.createSequentialGroup()
                        .add(panelBDLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(panelBDLayout.createSequentialGroup()
                                .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 239, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(panelBDLayout.createSequentialGroup()
                                .add(jLabel13)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 37, Short.MAX_VALUE)
                                .add(panelBDLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 210, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 239, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(905, 905, 905))))
        );
        panelBDLayout.setVerticalGroup(
            panelBDLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelBDLayout.createSequentialGroup()
                .add(92, 92, 92)
                .add(panelBDLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel12)
                    .add(panelBDLayout.createSequentialGroup()
                        .add(panelBDLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel9)
                            .add(jLabel10))
                        .add(17, 17, 17)
                        .add(jLabel11)))
                .add(56, 56, 56)
                .add(panelBDLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(jLabel8))
                .add(39, 39, 39)
                .add(panelBDLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(49, 49, 49)
                .add(jLabel15)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jTabbedPane1.addTab("tab3", panelBD);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1261, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
// TODO add your handling code here:
        Runtime rtt=Runtime.getRuntime();
        try {
            rtt.exec("cmd /c start  http://www.campus-telematika.com");
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
// TODO add your handling code here:
        jLabel8.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
// TODO add your handling code here:
        jLabel8.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel8MouseExited
    
    /**
     * Accede a la pagina web
     * @param evt evento
     */    
    /**
     * Cambia a noromal el cursor
     * @param evt
     */    
    /**
     * Cambia a mano el curosr
     * @param evt
     */    
    /**
     * Cambio de etiqueta
     * @param evt
     */
    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
// TODO add your handling code here:
        
    }//GEN-LAST:event_jTabbedPane1StateChanged
    
    /**
     * Lanza el asistente
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        VPaso1  vpa=new VPaso1();
        vpa.setVisible(true);
//        while(vpa.isVisible());
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * Abre la pagina web
     * @param evt
     */
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
// TODO add your handling code here:
        Runtime rtt=Runtime.getRuntime();
        try {
            rtt.exec("cmd /c start  https://www.agpd.es/index.php?idSeccion=93");
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jLabel5MouseClicked
    
    /**
     * cambia el cursor a normal
     * @param evt
     */
    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
// TODO add your handling code here:
        jLabel5.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel5MouseExited
    
    /**
     * cambia el cursor a mano
     * @param evt
     */
    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
// TODO add your handling code here:
        jLabel5.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel5MouseEntered
    
    RTFEditorKit editor;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel panelAPD;
    private javax.swing.JPanel panelBD;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JTextPane texto;
    private javax.swing.JTextField textoCIF;
    private javax.swing.JTextField textoEmail;
    private javax.swing.JTextField textoNombre;
    // End of variables declaration//GEN-END:variables
    
}
