/*
 * DialogoAuto.java
 *
 * Created on 9 de enero de 2006, 11:34
 */

package bgc.gui.proy.automat;

import bgc.bd.GestorBD;
import bgc.negocio.Cliente;
import bgc.negocio.proyecto.LeerProy;
import bgc.negocio.proyecto.Proyecto;
import bgc.negocio.proyecto.ProyectoAuto;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.Vector;
import javax.swing.JTable;

/**
 *
 * @author  Aitor
 */
public class DialogoAuto extends javax.swing.JDialog {
    
    
    PanelAbrir panel;
     File ficherito;
    Proyecto p;
    
    /** Creates new form DialogoAuto */
    public DialogoAuto(java.awt.Frame parent, boolean modal,File f) {
        super(parent, modal);
        initComponents();
    
	ficherito = f;
	initComponents();
//        panel=new PanelAbrir(f,this);
//        jLabel1.add(panel);
//        panel.setLocation(5,5);
//        panel.setSize(700, 400);
	inicializar();
        this.setSize(720,450);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(screenSize.width/2-getSize().width/2, screenSize.height/2-getSize().height/2);
       
       // ( (MetalInternalFrameUI)this.getUI() ).setNorthPane(null);
    }
    
    public void inicializar()
    {
	
	panel.textoNombre.setEnabled(false);
	panel.textoDescripcion.setEnabled(false);
	
	
	
	this.panel.tablaDestinatarios.setEnabled(false);
	
	
	LeerProy lectura = new LeerProy();
	try {
	    lectura.abrir(ficherito);
	} catch (IOException ex) {
	    ex.printStackTrace();
	}
	p = new Proyecto();
	p = lectura.leer(ficherito);
	this.panel.textoNombre.setText(p.getNombre());
	this.panel.textoDescripcion.setText(p.getDescripcion());
	
	if (p.getTipo().equals("Automatizado")){
	   panel.labelTipo.setText("Automatizado");
        }else if(p.getTipo().equals("Especial")){
            panel.labelTipo.setText("Especial");
        }

	
	
	
//	panel.textoDesc.setText(((ProyectoAuto)p).getDetalles());
	
        GestorBD gbd=new GestorBD();
	gbd.abrirBD();
	Vector v = gbd.obtenerListadoAbrir(p.getSql());
	gbd.cerrarBD();
	Object[][]ao=new Object[v.size()][10];
        for (int i=0;i<v.size();i++) {
            Cliente c=(Cliente)v.elementAt(i);
            ao[i][0]=c.getNombre() ;
            ao[i][1]=c.getApellido();
            ao[i][2]=c.getSexo();
            ao[i][3]=c.getDireccion();
            ao[i][4]=c.getCP();
            ao[i][5]=c.getCiudad();
            ao[i][6]=c.getProvincia();
            ao[i][7]=c.getTelefono();
            ao[i][8]=c.getMovil();
            ao[i][9]=c.getEmail();
        }
        panel.tablaDestinatarios.getTableHeader().setFont(new Font("Arial",Font.BOLD,12));
        panel.tablaDestinatarios.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        panel.tablaDestinatarios.setCellEditor(null);
        panel.tablaDestinatarios.enableInputMethods(false);
        panel.tablaDestinatarios.setAutoscrolls(true);
       
        panel.tablaDestinatarios.setModel(new javax.swing.table.DefaultTableModel(
                ao,
                new String [] {
            "Nombre", "Apellidos", "Sexo", "Dirección", "CP", "Ciudad", "Provincia", "Teléfono", "Móvil", "Email"
        }
        ));
        
        panel.tablaDestinatarios.getColumnModel().getColumn(0).setPreferredWidth(150);
        panel.tablaDestinatarios.getColumnModel().getColumn(1).setPreferredWidth(200);
        panel.tablaDestinatarios.getColumnModel().getColumn(2).setPreferredWidth(75);
        panel.tablaDestinatarios.getColumnModel().getColumn(3).setPreferredWidth(250);
        panel.tablaDestinatarios.getColumnModel().getColumn(4).setPreferredWidth(75);
        panel.tablaDestinatarios.getColumnModel().getColumn(5).setPreferredWidth(150);
        panel.tablaDestinatarios.getColumnModel().getColumn(6).setPreferredWidth(150);
        panel.tablaDestinatarios.getColumnModel().getColumn(7).setPreferredWidth(100);
        panel.tablaDestinatarios.getColumnModel().getColumn(8).setPreferredWidth(100);
        panel.tablaDestinatarios.getColumnModel().getColumn(9).setPreferredWidth(200);
	lectura.cerrar();
    
    }
    
    
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setBackground(new java.awt.Color(216, 228, 198));
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
