package bgc.gui.proy.automat;
import bgc.negocio.Dia;
import java.util.Hashtable;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JSpinner;
/**
 * La clase PanelSemanal ofrece la interfaz necesaria para escoger la
 * periodicidad semanal del envío del mailing
 *
 * @author Campus - Telematika, S.L.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */
public class PanelSemanal extends javax.swing.JPanel {
    
   /** Crea un nuevo jPanel PanelSemanal */
    public PanelSemanal() {
        initComponents();
        
           this.setSize(453, 360);
	    panelesHoras=new Hashtable();
	    panelesHoras.put("Lunes",PanelLunes);
	    panelesHoras.put("Martes",PanelMartes);
	    panelesHoras.put("Miercoles",PanelMiercoles);
	    panelesHoras.put("Jueves",PanelJueves);
	    panelesHoras.put("Viernes",PanelViernes);
	    panelesHoras.put("Sabado",PanelSabado);
	    panelesHoras.put("Domingo",PanelDomingo);
            jPanel1.setVisible(true);
            jPanel1.setSize(104, 360);
            PanelLunes.setSize(300, 40);
            PanelMartes.setSize(300, 40);
            PanelMiercoles.setSize(300, 40);
            PanelJueves.setSize(300, 40);
            PanelViernes.setSize(300, 40);
            PanelSabado.setSize(300, 40);
            PanelDomingo.setSize(300, 40);
//           desabilitar();
	    
	    for(int i=0;i<7;i++)
            {
                ((JPanel)panelesHoras.get(dias[i])).setVisible(false);
                ((JPanel)panelesHoras.get(dias[i])).setEnabled(false);
            }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        checkLunes = new javax.swing.JCheckBox();
        checkMartes = new javax.swing.JCheckBox();
        checkMiercoles = new javax.swing.JCheckBox();
        checkJueves = new javax.swing.JCheckBox();
        checkViernes = new javax.swing.JCheckBox();
        checkSabado = new javax.swing.JCheckBox();
        checkDomingo = new javax.swing.JCheckBox();
        PanelLunes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        PanelMartes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        PanelMiercoles = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        PanelJueves = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        jSpinner8 = new javax.swing.JSpinner();
        PanelViernes = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSpinner9 = new javax.swing.JSpinner();
        jSpinner10 = new javax.swing.JSpinner();
        PanelSabado = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSpinner11 = new javax.swing.JSpinner();
        jSpinner12 = new javax.swing.JSpinner();
        PanelDomingo = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSpinner13 = new javax.swing.JSpinner();
        jSpinner14 = new javax.swing.JSpinner();

        setLayout(null);

        setBackground(new java.awt.Color(240, 240, 240));
        setOpaque(false);
        jPanel1.setLayout(null);

        jPanel1.setOpaque(false);
        checkLunes.setText("Lunes");
        checkLunes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        checkLunes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkLunes.setOpaque(false);
        checkLunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLunesActionPerformed(evt);
            }
        });

        jPanel1.add(checkLunes);
        checkLunes.setBounds(20, 20, 60, 15);

        checkMartes.setText("Martes");
        checkMartes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        checkMartes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkMartes.setOpaque(false);
        checkMartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLunesActionPerformed(evt);
            }
        });

        jPanel1.add(checkMartes);
        checkMartes.setBounds(20, 70, 60, 15);

        checkMiercoles.setText("Miercoles");
        checkMiercoles.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        checkMiercoles.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkMiercoles.setOpaque(false);
        checkMiercoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLunesActionPerformed(evt);
            }
        });

        jPanel1.add(checkMiercoles);
        checkMiercoles.setBounds(20, 120, 80, 15);

        checkJueves.setText("Jueves");
        checkJueves.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        checkJueves.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkJueves.setOpaque(false);
        checkJueves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLunesActionPerformed(evt);
            }
        });

        jPanel1.add(checkJueves);
        checkJueves.setBounds(20, 170, 60, 15);

        checkViernes.setText("Viernes");
        checkViernes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        checkViernes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkViernes.setOpaque(false);
        checkViernes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLunesActionPerformed(evt);
            }
        });

        jPanel1.add(checkViernes);
        checkViernes.setBounds(20, 220, 80, 15);

        checkSabado.setText("Sabado");
        checkSabado.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        checkSabado.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkSabado.setOpaque(false);
        checkSabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLunesActionPerformed(evt);
            }
        });

        jPanel1.add(checkSabado);
        checkSabado.setBounds(20, 270, 60, 15);

        checkDomingo.setText("Domingo");
        checkDomingo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        checkDomingo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkDomingo.setOpaque(false);
        checkDomingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLunesActionPerformed(evt);
            }
        });

        jPanel1.add(checkDomingo);
        checkDomingo.setBounds(20, 310, 70, 15);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 110, 360);

        PanelLunes.setOpaque(false);
        jLabel1.setText("Hora");

        jLabel2.setText("Minuto");

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PanelLunesLayout = new org.jdesktop.layout.GroupLayout(PanelLunes);
        PanelLunes.setLayout(PanelLunesLayout);
        PanelLunesLayout.setHorizontalGroup(
            PanelLunesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelLunesLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(18, 18, 18)
                .add(jSpinner1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(69, 69, 69)
                .add(jLabel2)
                .add(21, 21, 21)
                .add(jSpinner2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        PanelLunesLayout.setVerticalGroup(
            PanelLunesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelLunesLayout.createSequentialGroup()
                .addContainerGap()
                .add(PanelLunesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jSpinner1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2)
                    .add(jSpinner2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        add(PanelLunes);
        PanelLunes.setBounds(120, 10, 300, 10);

        PanelMartes.setOpaque(false);
        jLabel3.setText("Hora");

        jLabel4.setText("Minuto");

        jSpinner3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jSpinner4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PanelMartesLayout = new org.jdesktop.layout.GroupLayout(PanelMartes);
        PanelMartes.setLayout(PanelMartesLayout);
        PanelMartesLayout.setHorizontalGroup(
            PanelMartesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelMartesLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .add(18, 18, 18)
                .add(jSpinner3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(69, 69, 69)
                .add(jLabel4)
                .add(21, 21, 21)
                .add(jSpinner4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        PanelMartesLayout.setVerticalGroup(
            PanelMartesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelMartesLayout.createSequentialGroup()
                .addContainerGap()
                .add(PanelMartesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jSpinner3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(jSpinner4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        add(PanelMartes);
        PanelMartes.setBounds(120, 60, 300, 10);

        PanelMiercoles.setOpaque(false);
        jLabel5.setText("Hora");

        jLabel6.setText("Minuto");

        jSpinner5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jSpinner6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PanelMiercolesLayout = new org.jdesktop.layout.GroupLayout(PanelMiercoles);
        PanelMiercoles.setLayout(PanelMiercolesLayout);
        PanelMiercolesLayout.setHorizontalGroup(
            PanelMiercolesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelMiercolesLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel5)
                .add(18, 18, 18)
                .add(jSpinner5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(70, 70, 70)
                .add(jLabel6)
                .add(21, 21, 21)
                .add(jSpinner6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        PanelMiercolesLayout.setVerticalGroup(
            PanelMiercolesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelMiercolesLayout.createSequentialGroup()
                .addContainerGap()
                .add(PanelMiercolesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jSpinner5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6)
                    .add(jSpinner6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        add(PanelMiercoles);
        PanelMiercoles.setBounds(120, 110, 290, 10);

        PanelJueves.setOpaque(false);
        jLabel7.setText("Hora");

        jLabel8.setText("Minuto");

        jSpinner7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jSpinner8.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PanelJuevesLayout = new org.jdesktop.layout.GroupLayout(PanelJueves);
        PanelJueves.setLayout(PanelJuevesLayout);
        PanelJuevesLayout.setHorizontalGroup(
            PanelJuevesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelJuevesLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel7)
                .add(18, 18, 18)
                .add(jSpinner7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(70, 70, 70)
                .add(jLabel8)
                .add(21, 21, 21)
                .add(jSpinner8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        PanelJuevesLayout.setVerticalGroup(
            PanelJuevesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelJuevesLayout.createSequentialGroup()
                .addContainerGap()
                .add(PanelJuevesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(jSpinner7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8)
                    .add(jSpinner8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        add(PanelJueves);
        PanelJueves.setBounds(120, 160, 300, 10);

        PanelViernes.setOpaque(false);
        jLabel9.setText("Hora");

        jLabel10.setText("Minuto");

        jSpinner9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jSpinner10.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PanelViernesLayout = new org.jdesktop.layout.GroupLayout(PanelViernes);
        PanelViernes.setLayout(PanelViernesLayout);
        PanelViernesLayout.setHorizontalGroup(
            PanelViernesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelViernesLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel9)
                .add(18, 18, 18)
                .add(jSpinner9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(70, 70, 70)
                .add(jLabel10)
                .add(21, 21, 21)
                .add(jSpinner10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        PanelViernesLayout.setVerticalGroup(
            PanelViernesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelViernesLayout.createSequentialGroup()
                .addContainerGap()
                .add(PanelViernesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(jSpinner9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10)
                    .add(jSpinner10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        add(PanelViernes);
        PanelViernes.setBounds(120, 210, 290, 10);

        PanelSabado.setOpaque(false);
        jLabel11.setText("Hora");

        jLabel12.setText("Minuto");

        jSpinner11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jSpinner12.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PanelSabadoLayout = new org.jdesktop.layout.GroupLayout(PanelSabado);
        PanelSabado.setLayout(PanelSabadoLayout);
        PanelSabadoLayout.setHorizontalGroup(
            PanelSabadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelSabadoLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel11)
                .add(18, 18, 18)
                .add(jSpinner11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(71, 71, 71)
                .add(jLabel12)
                .add(21, 21, 21)
                .add(jSpinner12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        PanelSabadoLayout.setVerticalGroup(
            PanelSabadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelSabadoLayout.createSequentialGroup()
                .addContainerGap()
                .add(PanelSabadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(jSpinner11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12)
                    .add(jSpinner12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        add(PanelSabado);
        PanelSabado.setBounds(120, 260, 290, 10);

        PanelDomingo.setOpaque(false);
        jLabel13.setText("Hora");

        jLabel14.setText("Minuto");

        jSpinner13.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jSpinner14.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PanelDomingoLayout = new org.jdesktop.layout.GroupLayout(PanelDomingo);
        PanelDomingo.setLayout(PanelDomingoLayout);
        PanelDomingoLayout.setHorizontalGroup(
            PanelDomingoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelDomingoLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel13)
                .add(18, 18, 18)
                .add(jSpinner13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(72, 72, 72)
                .add(jLabel14)
                .add(21, 21, 21)
                .add(jSpinner14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        PanelDomingoLayout.setVerticalGroup(
            PanelDomingoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelDomingoLayout.createSequentialGroup()
                .addContainerGap()
                .add(PanelDomingoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(jSpinner13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel14)
                    .add(jSpinner14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        add(PanelDomingo);
        PanelDomingo.setBounds(120, 300, 290, 10);

    }// </editor-fold>//GEN-END:initComponents
/**Modifica el valor de los minutos*/
    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
// TODO add your handling code here:
        JSpinner jsh=(JSpinner)evt.getSource();
	if (((Integer)jsh.getValue()).intValue()==-1)
		jsh.setValue(new Integer(0));
	if (((Integer)jsh.getValue()).intValue()==60)
		jsh.setValue(new Integer(59));
    }//GEN-LAST:event_jSpinner2StateChanged
/**Modifica el valor de las horas*/
    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
// TODO add your handling code here:
            JSpinner jsh=(JSpinner)evt.getSource();
	    if (((Integer)jsh.getValue()).intValue()==-1)
		jsh.setValue(new Integer(0));
	    if (((Integer)jsh.getValue()).intValue()==24)
		jsh.setValue(new Integer(23));
    }//GEN-LAST:event_jSpinner1StateChanged
/**Muestra u oculta el panel correspondiente (vale para todos los dias)*/
    private void checkLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLunesActionPerformed
// TODO add your handling code here:
        
            JCheckBox jc=(JCheckBox)evt.getSource();
	    
	    if (jc.isSelected()) {
		((JPanel)panelesHoras.get(jc.getText())).setVisible(true);
	    }else {
		((JPanel)panelesHoras.get(jc.getText())).setVisible(false);
	    }
    }//GEN-LAST:event_checkLunesActionPerformed
   /**Devuelve el estado del checkBox del domingo*/
    public javax.swing.JCheckBox getCheckDomingo() {
        return checkDomingo;
    }
 /**Devuelve el estado del checkBox del jueves*/
    public javax.swing.JCheckBox getCheckJueves() {
        return checkJueves;
    }
 /**Devuelve el estado del checkBox del lunes*/
    public javax.swing.JCheckBox getCheckLunes() {
        return checkLunes;
    }
 /**Devuelve el estado del checkBox del martes*/
    public javax.swing.JCheckBox getCheckMartes() {
        return checkMartes;
    }
 /**Devuelve el estado del checkBox del miercoles*/
    public javax.swing.JCheckBox getCheckMiercoles() {
        return checkMiercoles;
    }
 /**Devuelve el estado del checkBox del sabado*/
    public javax.swing.JCheckBox getCheckSabado() {
        return checkSabado;
    }
 /**Devuelve el estado del checkBox del viernes*/
    public javax.swing.JCheckBox getCheckViernes() {
        return checkViernes;
    }
        
       /**Deshabilita los paneles de las horas de cada dia*/ 
     private void desabilitar()
        {
         for(int i=0;i<PanelLunes.getComponentCount();i++)
                PanelLunes.getComponent(i).setEnabled(false);
          for(int i=0;i<PanelMartes.getComponentCount();i++)
                PanelMartes.getComponent(i).setEnabled(false);
          for(int i=0;i<PanelMiercoles.getComponentCount();i++)
                PanelMiercoles.getComponent(i).setEnabled(false);
          for(int i=0;i<PanelJueves.getComponentCount();i++)
                PanelJueves.getComponent(i).setEnabled(false);
          for(int i=0;i<PanelViernes.getComponentCount();i++)
                PanelViernes.getComponent(i).setEnabled(false);
          for(int i=0;i<PanelLunes.getComponentCount();i++)
                PanelSabado.getComponent(i).setEnabled(false);
          for(int i=0;i<PanelLunes.getComponentCount();i++)
                PanelSabado.getComponent(i).setEnabled(false);
          for(int i=0;i<PanelDomingo.getComponentCount();i++)
                PanelDomingo.getComponent(i).setEnabled(false);
         
         checkLunes.setEnabled(false);
         checkMartes.setEnabled(false);
         checkMiercoles.setEnabled(false);
         checkJueves.setEnabled(false);
         checkViernes.setEnabled(false);
         checkSabado.setEnabled(false);
         checkDomingo.setEnabled(false);
         
        }
    
    /**Habilita y muestra el panel del domingo*/
      public void marcarDomingo(int h,int m)
    {
        checkDomingo.setSelected(true);
        ((JPanel)panelesHoras.get("Domingo")).setVisible(true);
        jSpinner13.setValue( new Integer(h));
        jSpinner14.setValue( new Integer(m));
    }
    /**Habilita y muestra el panel del lunes*/
    public void marcarLunes(int h,int m)
    {
        checkLunes.setSelected(true);
        checkLunes.doClick();
        ((JPanel)panelesHoras.get("Lunes")).setVisible(true);
        jSpinner1.setValue( new Integer(h));
        jSpinner2.setValue( new Integer(m));
    }
    /**Habilita y muestra el panel del martes*/
    public void marcarMartes(int h,int m)
    {
        checkMartes.doClick();//setSelected(true);
        ((JPanel)panelesHoras.get("Martes")).setVisible(true);
        jSpinner3.setValue( new Integer(h));
        jSpinner4.setValue( new Integer(m));
    }
    /**Habilita y muestra el panel del miercoles*/
    public void marcarMiercoles(int h,int m)
    {
        checkMiercoles.doClick();//setSelected(true);
        ((JPanel)panelesHoras.get("Miercoles")).setVisible(true);
        jSpinner5.setValue( new Integer(h));
        jSpinner6.setValue( new Integer(m));
    }
    /**Habilita y muestra el panel del jueves*/
    public void marcarJueves(int h,int m)
    {
        checkJueves.doClick();//.setSelected(true);
        ((JPanel)panelesHoras.get("Jueves")).setVisible(true);
        jSpinner7.setValue( new Integer(h));
        jSpinner8.setValue( new Integer(m));
    }
    /**Habilita y muestra el panel del viernes*/
    public void marcarViernes(int h,int m)
    {
        checkViernes.doClick();//.setSelected(true);
        ((JPanel)panelesHoras.get("Viernes")).setVisible(true);
        jSpinner9.setValue( new Integer(h));
        jSpinner10.setValue( new Integer(m));
    }
    /**Habilita y muestra el panel del sabado*/
    public void marcarSabado(int h,int m)
    {
        checkSabado.doClick();//.setSelected(true);
        ((JPanel)panelesHoras.get("Sabado")).setVisible(true);
        jSpinner11.setValue( new Integer(h));
        jSpinner12.setValue( new Integer(m));
    }
     
     /**Devuelve un array con los días seleccionados*/
    public Dia[] getDiasSelec() {
	    Dia[]ad=new Dia[7];
	    
	    for(int i=0;i<7;i++) {
		ad[i]=null;
		if (((JPanel)panelesHoras.get(dias[i])).isVisible() ) {
		    Dia d=new Dia();
		    d.setDia(i);
		    d.setHora( ((Integer) ((JSpinner)((JPanel)panelesHoras.get(dias[i])).getComponent(1)).getValue()).intValue() );
		    d.setMin( ((Integer) ((JSpinner)((JPanel)panelesHoras.get(dias[i])).getComponent(3)).getValue()).intValue() );
		    ad[i]=d;
		}
	    }
	    
	    return ad;
	}
    
    /**Array de dias de la semana*/
    String[]dias={"Lunes","Martes","Miercoles","Jueves","Viernes","Sabado","Domingo"};
    /**Tabla de mapeo para los paneles de las horas*/
    private Hashtable panelesHoras;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDomingo;
    private javax.swing.JPanel PanelJueves;
    private javax.swing.JPanel PanelLunes;
    private javax.swing.JPanel PanelMartes;
    private javax.swing.JPanel PanelMiercoles;
    private javax.swing.JPanel PanelSabado;
    private javax.swing.JPanel PanelViernes;
    private javax.swing.JCheckBox checkDomingo;
    private javax.swing.JCheckBox checkJueves;
    private javax.swing.JCheckBox checkLunes;
    private javax.swing.JCheckBox checkMartes;
    private javax.swing.JCheckBox checkMiercoles;
    private javax.swing.JCheckBox checkSabado;
    private javax.swing.JCheckBox checkViernes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner13;
    private javax.swing.JSpinner jSpinner14;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    // End of variables declaration//GEN-END:variables
    
}
