package bgc.gui.proy.automat;
import bgc.bd.GestorBD;
import bgc.gui.inicio.VInicio;
import bgc.negocio.proyecto.LeerProy;
import bgc.negocio.proyecto.ProyectoAuto;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.lang.reflect.Array;
import javax.swing.border.TitledBorder;
/**
 * La clase PanelAuto ofrece la interfaz necesaria para listar, visualizar los detalles y
 * eliminar los proyectos automatizados en curso
 *
 * @author Campus - Telematika, S.L.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */
public class PanelAuto extends javax.swing.JPanel {
    /**Proyecto automatizado*/
    ProyectoAuto p;
    /**Ventana contenedora del panel PanelAuto*/
    VAutomat padre;
    /**Array de jLabels con los proyectos*/
    JLabel [] Proyectos;
    /**Vector de proyectos automatizados*/
    Vector vpa;
    /**Posición de proyecto automatizado dentro dl vector*/
    static  int posicion;
    /** Crea una nueva instancia de PanelAuto */
    public PanelAuto(VAutomat padre) {
        initComponents();
        this.padre=padre;
        Proyectos=new JLabel[50];
        cargarDatosProyectos();
        this.setSize(553, 281);
      //  this.jScrollPane1.setOpaque(false);
        this.jPanel1.setOpaque(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        popMenu = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jMenuItem1.setText("Eliminar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });

        popMenu.add(jMenuItem1);

        jMenuItem2.setText("Ver Detalles");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });

        popMenu.add(jMenuItem2);

        setBackground(new java.awt.Color(216, 228, 198));
        setOpaque(false);
        jButton1.setBackground(new java.awt.Color(240, 240, 240));
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Proyectos Programados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 153, 0)));
        jPanel1.setOpaque(false);
        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 920, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 436, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jButton1)
                        .add(418, 418, 418))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**Elimina el proyecto sobre el qe se ha hecho clic con el boton derecho*/
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
// TODO add your handling code here:
        Object []botones={"Eliminar","Cancelar"};
        if(JOptionPane.showOptionDialog(null,"¿Desea eliminar el mailing?","Confirmación de eliminación",JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE,null,botones,botones[0])==JOptionPane.OK_OPTION) {
            eliminarProyecto(posicion);
            cargarDatosProyectos();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    /**Muestra los detalles del proyecto sobre el qe se ha hecho clic con el boton derecho*/
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
// TODO add your handling code here:
        String nf=(String)vpa.elementAt(posicion);
        VDialogoAuto v=new VDialogoAuto(new File(nf)); 
         ((VAutomat)this.getParent().getParent().getParent().getParent().getParent()).getParent().add(v);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
      
        v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2);
        v.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    /**Vuelve a la pantalla de inicio*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        VInicio v = new VInicio();
        this.padre.getParent().add(v);
        this.padre.dispose();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2);
        v.show();
        
    }//GEN-LAST:event_jButton1ActionPerformed
   /**Muestra los detalles del proyecto sobre el qe se ha hecho clic*/
    private void textoMouseClicked(java.awt.event.MouseEvent evt,int pos) {
// TODO add your handling code here:
        
        
        String nf=(String)vpa.elementAt(pos);
        
        VDialogoAuto v=new VDialogoAuto(new File(nf));
        ((VAutomat)this.getParent().getParent().getParent().getParent().getParent()).getParent().add(v);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
       
        v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2);
        v.show();
     
    }
    /**Carga los datos de los proyectos automatizados para su listado y visualización*/
    public void cargarDatosProyectos() {
        int cont =0;
        jPanel1.removeAll();
        GestorBD gbd=new GestorBD();
        gbd.abrirBD();
        vpa=gbd.obtenerProyectosAutomatizados();
        gbd.cerrarBD();
        cont=vpa.size();
        ((TitledBorder)this.jPanel1.getBorder()).setTitleColor(new Color(219,129,0));
        ((TitledBorder)this.jPanel1.getBorder()).setTitleFont(new Font("",Font.BOLD,12));
        ((TitledBorder)this.jPanel1.getBorder()).setTitleJustification(TitledBorder.CENTER);
        switch(cont) {
            case 0:  {((TitledBorder)this.jPanel1.getBorder()).setTitle("No existen proyectos programados");
                
            
            }break;
            
            case 1:  {
                ((TitledBorder)this.jPanel1.getBorder()).setTitle("Existe "+cont+" proyecto programado");
                String nf=(String)vpa.elementAt(0);
                LeerProy lf=new LeerProy();
                try {
                    lf.abrir(new File(nf));
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
                p=(ProyectoAuto)lf.leer(new File(nf));
                lf.cerrar();
      
                Proyectos[0]=new JLabel(" Proyecto:  "+p.getNombre()+"                    Descripcion: "+p.getDescripcion());
                Proyectos[0].setBackground(Color.red);
                Proyectos[0].setSize(400,30);
                Proyectos[0].setLocation( 5 , 15 );
                jPanel1.add(Proyectos[0]);
                this.jPanel1.validate();
                this.jPanel1.repaint();
                Proyectos[0].addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        if (evt.getButton()==java.awt.event.MouseEvent.BUTTON3 ) {
                            posicion=0;
                            popMenu.show(((JLabel)evt.getSource()),evt.getX(),evt.getY());
                            
                        } else{
                            textoMouseClicked(evt,0);
                        }}
                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        Proyectos[0].setCursor(new Cursor(Cursor.HAND_CURSOR));
                        Proyectos[0].setForeground(Color.blue);
                    }
                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        Proyectos[0].setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                        Proyectos[0].setForeground(Color.black);
                    }
                    
                });
                
            }break;
            
            default: { ((TitledBorder)this.jPanel1.getBorder()).setTitle("Existen "+cont+" proyectos programados");
            
            for(int i=0;i<vpa.size();i++) {
                String nf=(String)vpa.elementAt(i);
                LeerProy lf=new LeerProy();
                try {
                    lf.abrir(new File(nf));
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
                p=(ProyectoAuto)lf.leer(new File(nf));
                lf.cerrar();
                Proyectos[i]=new JLabel(" Proyecto: "+p.getNombre()+"                      Descripción: "+p.getDescripcion());
                Proyectos[i].setBackground(Color.red);
                Proyectos[i].setSize(400,30);
                
                Proyectos[i].setLocation( 5 , 30*(i)+15 );
                jPanel1.add(Proyectos[i]);
                this.jPanel1.validate();
                this.jPanel1.repaint();
                final int posi=i;
                Proyectos[i].addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        if (evt.getButton()==java.awt.event.MouseEvent.BUTTON3 ) {
                            posicion=posi;
                            popMenu.show(((JLabel)evt.getSource()),evt.getX(),evt.getY());
                            
                        } else{
                            textoMouseClicked(evt,posi);
                        }
                    }
                    
                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        Proyectos[posi].setCursor(new Cursor(Cursor.HAND_CURSOR));
                        Proyectos[posi].setForeground(Color.blue);
                    }
                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        Proyectos[posi].setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                        Proyectos[posi].setForeground(Color.black);
                    }});
            }
            }
        }
    }
/**Elimina un proyecto automatizado de la base de datos y del disco duro*/
    public void eliminarProyecto(int pos) {
        GestorBD gbd=new GestorBD();
        gbd.abrirBD();
        String ruta=gbd.eliminarProyAuto(((String)vpa.get(pos)));
        gbd.cerrarBD();
        File f=new File(ruta.substring(0,ruta.lastIndexOf(System.getProperty("file.separator"))));
        int tam=Array.getLength(f.listFiles());
        for(int i=0;i<tam;i++)
            f.listFiles()[0].delete();
        f.delete();
        
        this.jPanel1.validate();
        this.jPanel1.repaint();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu popMenu;
    // End of variables declaration//GEN-END:variables
    
}
