/*
 * VDetallesTipo.java
 *
 * Created on 2 de noviembre de 2005, 12:43
 */

package bgc.gui.proy.automat;

import bgc.negocio.Dia;
import bgc.negocio.proyecto.Proyecto;
import bgc.negocio.proyecto.ProyectoAuto;
import java.awt.Frame;
import java.util.Hashtable;
import javax.swing.JCheckBox;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import java.awt.Dimension;
import java.awt.Toolkit;
import com.toedter.calendar.*;

/**
 *
 * @author  Fernando
 */
public class VDetallesTipo extends javax.swing.JDialog {
    
    
//    class PanelSemanal extends javax.swing.JPanel {
//	
//	/** Creates new form PanelSemanal */
//	public PanelSemanal() {
//	    initComponents();
//	    
//	    
//	    panelesHoras=new Hashtable();
//	    panelesHoras.put("Lunes",panelHoraLunes);
//	    panelesHoras.put("Martes",panelHoraMartes);
//	    panelesHoras.put("Miercoles",panelHoraMiercoles);
//	    panelesHoras.put("Jueves",panelHoraJueves);
//	    panelesHoras.put("Viernes",panelHoraViernes);
//	    panelesHoras.put("Sabado",panelHoraSabado);
//	    panelesHoras.put("Domingo",panelHoraDomingo);
//            
//           desabilitar();
//	    
//	    for(int i=0;i<7;i++)
//            {
//                ((JPanel)panelesHoras.get(dias[i])).setVisible(false);
//                ((JPanel)panelesHoras.get(dias[i])).setEnabled(false);
//            }
//	    
//	}
//	
//        
//        private void desabilitar()
//        {
//         for(int i=0;i<panelHoraLunes.getComponentCount();i++)
//                panelHoraLunes.getComponent(i).setEnabled(false);
//          for(int i=0;i<panelHoraMartes.getComponentCount();i++)
//                panelHoraMartes.getComponent(i).setEnabled(false);
//          for(int i=0;i<panelHoraMiercoles.getComponentCount();i++)
//                panelHoraMiercoles.getComponent(i).setEnabled(false);
//          for(int i=0;i<panelHoraJueves.getComponentCount();i++)
//                panelHoraJueves.getComponent(i).setEnabled(false);
//          for(int i=0;i<panelHoraViernes.getComponentCount();i++)
//                panelHoraViernes.getComponent(i).setEnabled(false);
//          for(int i=0;i<panelHoraLunes.getComponentCount();i++)
//                panelHoraSabado.getComponent(i).setEnabled(false);
//          for(int i=0;i<panelHoraLunes.getComponentCount();i++)
//                panelHoraSabado.getComponent(i).setEnabled(false);
//          for(int i=0;i<panelHoraDomingo.getComponentCount();i++)
//                panelHoraDomingo.getComponent(i).setEnabled(false);
//         
//         checkLunes.setEnabled(false);
//         checkMartes.setEnabled(false);
//         checkMiercoles.setEnabled(false);
//         checkJueves.setEnabled(false);
//         checkViernes.setEnabled(false);
//         checkSabado.setEnabled(false);
//         checkDomingo.setEnabled(false);
//         
//        }
//        
//	/** This method is called from within the constructor to
//	 * initialize the form.
//	 * WARNING: Do NOT modify this code. The content of this method is
//	 * always regenerated by the Form Editor.
//	 */
//	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
//	private void initComponents() {
//	    jPanel2 = new javax.swing.JPanel();
//	    checkLunes = new javax.swing.JCheckBox();
//	    checkMartes = new javax.swing.JCheckBox();
//	    checkMiercoles = new javax.swing.JCheckBox();
//	    checkJueves = new javax.swing.JCheckBox();
//	    checkViernes = new javax.swing.JCheckBox();
//	    checkSabado = new javax.swing.JCheckBox();
//	    checkDomingo = new javax.swing.JCheckBox();
//	    panelHoras = new javax.swing.JPanel();
//	    panelHoraLunes = new javax.swing.JPanel();
//	    jSpinner1 = new javax.swing.JSpinner();
//	    jSpinner2 = new javax.swing.JSpinner();
//	    jLabel1 = new javax.swing.JLabel();
//	    jLabel2 = new javax.swing.JLabel();
//	    panelHoraMartes = new javax.swing.JPanel();
//	    jSpinner3 = new javax.swing.JSpinner();
//	    jSpinner4 = new javax.swing.JSpinner();
//	    jLabel3 = new javax.swing.JLabel();
//	    jLabel4 = new javax.swing.JLabel();
//	    panelHoraMiercoles = new javax.swing.JPanel();
//	    jSpinner5 = new javax.swing.JSpinner();
//	    jSpinner6 = new javax.swing.JSpinner();
//	    jLabel5 = new javax.swing.JLabel();
//	    jLabel6 = new javax.swing.JLabel();
//	    panelHoraJueves = new javax.swing.JPanel();
//	    jSpinner7 = new javax.swing.JSpinner();
//	    jSpinner8 = new javax.swing.JSpinner();
//	    jLabel7 = new javax.swing.JLabel();
//	    jLabel8 = new javax.swing.JLabel();
//	    panelHoraViernes = new javax.swing.JPanel();
//	    jSpinner9 = new javax.swing.JSpinner();
//	    jSpinner10 = new javax.swing.JSpinner();
//	    jLabel9 = new javax.swing.JLabel();
//	    jLabel10 = new javax.swing.JLabel();
//	    panelHoraSabado = new javax.swing.JPanel();
//	    jSpinner11 = new javax.swing.JSpinner();
//	    jSpinner12 = new javax.swing.JSpinner();
//	    jLabel11 = new javax.swing.JLabel();
//	    jLabel12 = new javax.swing.JLabel();
//	    panelHoraDomingo = new javax.swing.JPanel();
//	    jSpinner13 = new javax.swing.JSpinner();
//	    jSpinner14 = new javax.swing.JSpinner();
//	    jLabel13 = new javax.swing.JLabel();
//	    jLabel14 = new javax.swing.JLabel();
//	    
//	    jPanel2.setLayout(new java.awt.GridLayout(7, 1));
//	    
//	    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
//	    checkLunes.setText("Lunes");
//	    checkLunes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
//	    checkLunes.setMargin(new java.awt.Insets(0, 0, 0, 0));
//	    checkLunes.addItemListener(new java.awt.event.ItemListener() {
//		public void itemStateChanged(java.awt.event.ItemEvent evt) {
//		    checkLunesItemStateChanged(evt);
//		}
//	    });
//	    
//	    jPanel2.add(checkLunes);
//	    
//	    checkMartes.setText("Martes");
//	    checkMartes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
//	    checkMartes.setMargin(new java.awt.Insets(0, 0, 0, 0));
//	    checkMartes.addItemListener(new java.awt.event.ItemListener() {
//		public void itemStateChanged(java.awt.event.ItemEvent evt) {
//		    checkLunesItemStateChanged(evt);
//		}
//	    });
//	    
//	    jPanel2.add(checkMartes);
//	    
//	    checkMiercoles.setText("Miercoles");
//	    checkMiercoles.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
//	    checkMiercoles.setMargin(new java.awt.Insets(0, 0, 0, 0));
//	    checkMiercoles.addItemListener(new java.awt.event.ItemListener() {
//		public void itemStateChanged(java.awt.event.ItemEvent evt) {
//		    checkLunesItemStateChanged(evt);
//		}
//	    });
//	    
//	    jPanel2.add(checkMiercoles);
//	    
//	    checkJueves.setText("Jueves");
//	    checkJueves.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
//	    checkJueves.setMargin(new java.awt.Insets(0, 0, 0, 0));
//	    checkJueves.addItemListener(new java.awt.event.ItemListener() {
//		public void itemStateChanged(java.awt.event.ItemEvent evt) {
//		    checkLunesItemStateChanged(evt);
//		}
//	    });
//	    
//	    jPanel2.add(checkJueves);
//	    
//	    checkViernes.setText("Viernes");
//	    checkViernes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
//	    checkViernes.setMargin(new java.awt.Insets(0, 0, 0, 0));
//	    checkViernes.addItemListener(new java.awt.event.ItemListener() {
//		public void itemStateChanged(java.awt.event.ItemEvent evt) {
//		    checkLunesItemStateChanged(evt);
//		}
//	    });
//	    
//	    jPanel2.add(checkViernes);
//	    
//	    checkSabado.setText("Sabado");
//	    checkSabado.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
//	    checkSabado.setMargin(new java.awt.Insets(0, 0, 0, 0));
//	    checkSabado.addItemListener(new java.awt.event.ItemListener() {
//		public void itemStateChanged(java.awt.event.ItemEvent evt) {
//		    checkLunesItemStateChanged(evt);
//		}
//	    });
//	    
//	    jPanel2.add(checkSabado);
//	    
//	    checkDomingo.setText("Domingo");
//	    checkDomingo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
//	    checkDomingo.setMargin(new java.awt.Insets(0, 0, 0, 0));
//	    checkDomingo.addItemListener(new java.awt.event.ItemListener() {
//		public void itemStateChanged(java.awt.event.ItemEvent evt) {
//		    checkLunesItemStateChanged(evt);
//		}
//	    });
//	    
//	    jPanel2.add(checkDomingo);
//	    
//	    panelHoras.setLayout(new java.awt.GridLayout(7, 1));
//	    
//	    panelHoras.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
//	    jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
//		public void stateChanged(javax.swing.event.ChangeEvent evt) {
//		    jSpinner1StateChanged(evt);
//		}
//	    });
//	    
//	    jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
//		public void stateChanged(javax.swing.event.ChangeEvent evt) {
//		    jSpinner2StateChanged(evt);
//		}
//	    });
//	    
//	    jLabel1.setText("Horas");
//	    
//	    jLabel2.setText("Minutos");
//	    
//	    org.jdesktop.layout.GroupLayout panelHoraLunesLayout = new org.jdesktop.layout.GroupLayout(panelHoraLunes);
//	    panelHoraLunes.setLayout(panelHoraLunesLayout);
//	    panelHoraLunesLayout.setHorizontalGroup(
//	    panelHoraLunesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.LEADING, panelHoraLunesLayout.createSequentialGroup()
//	    .addContainerGap()
//	    .add(jSpinner1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//	    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(21, 21, 21)
//	    .add(jSpinner2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//	    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addContainerGap(61, Short.MAX_VALUE))
//	    );
//	    panelHoraLunesLayout.setVerticalGroup(
//	    panelHoraLunesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.LEADING, panelHoraLunesLayout.createSequentialGroup()
//	    .addContainerGap()
//	    .add(panelHoraLunesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelHoraLunesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//	    .add(jSpinner1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//	    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelHoraLunesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//	    .add(jSpinner2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
//	    .addContainerGap())
//	    );
//	    panelHoras.add(panelHoraLunes);
//	    
//	    jSpinner3.addChangeListener(new javax.swing.event.ChangeListener() {
//		public void stateChanged(javax.swing.event.ChangeEvent evt) {
//		    jSpinner1StateChanged(evt);
//		}
//	    });
//	    
//	    jSpinner4.addChangeListener(new javax.swing.event.ChangeListener() {
//		public void stateChanged(javax.swing.event.ChangeEvent evt) {
//		    jSpinner2StateChanged(evt);
//		}
//	    });
//	    
//	    jLabel3.setText("Horas");
//	    
//	    jLabel4.setText("Minutos");
//	    
//	    org.jdesktop.layout.GroupLayout panelHoraMartesLayout = new org.jdesktop.layout.GroupLayout(panelHoraMartes);
//	    panelHoraMartes.setLayout(panelHoraMartesLayout);
//	    panelHoraMartesLayout.setHorizontalGroup(
//	    panelHoraMartesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.LEADING, panelHoraMartesLayout.createSequentialGroup()
//	    .addContainerGap()
//	    .add(jSpinner3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//	    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(21, 21, 21)
//	    .add(jSpinner4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//	    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addContainerGap(61, Short.MAX_VALUE))
//	    );
//	    panelHoraMartesLayout.setVerticalGroup(
//	    panelHoraMartesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.LEADING, panelHoraMartesLayout.createSequentialGroup()
//	    .addContainerGap()
//	    .add(panelHoraMartesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelHoraMartesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//	    .add(jSpinner3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//	    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelHoraMartesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//	    .add(jSpinner4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
//	    .addContainerGap())
//	    );
//	    panelHoras.add(panelHoraMartes);
//	    
//	    jSpinner5.addChangeListener(new javax.swing.event.ChangeListener() {
//		public void stateChanged(javax.swing.event.ChangeEvent evt) {
//		    jSpinner1StateChanged(evt);
//		}
//	    });
//	    
//	    jSpinner6.addChangeListener(new javax.swing.event.ChangeListener() {
//		public void stateChanged(javax.swing.event.ChangeEvent evt) {
//		    jSpinner2StateChanged(evt);
//		}
//	    });
//	    
//	    jLabel5.setText("Horas");
//	    
//	    jLabel6.setText("Minutos");
//	    
//	    org.jdesktop.layout.GroupLayout panelHoraMiercolesLayout = new org.jdesktop.layout.GroupLayout(panelHoraMiercoles);
//	    panelHoraMiercoles.setLayout(panelHoraMiercolesLayout);
//	    panelHoraMiercolesLayout.setHorizontalGroup(
//	    panelHoraMiercolesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.LEADING, panelHoraMiercolesLayout.createSequentialGroup()
//	    .addContainerGap()
//	    .add(jSpinner5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//	    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(21, 21, 21)
//	    .add(jSpinner6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//	    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addContainerGap(61, Short.MAX_VALUE))
//	    );
//	    panelHoraMiercolesLayout.setVerticalGroup(
//	    panelHoraMiercolesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.LEADING, panelHoraMiercolesLayout.createSequentialGroup()
//	    .addContainerGap()
//	    .add(panelHoraMiercolesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelHoraMiercolesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//	    .add(jSpinner5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//	    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelHoraMiercolesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//	    .add(jSpinner6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
//	    .addContainerGap())
//	    );
//	    panelHoras.add(panelHoraMiercoles);
//	    
//	    jSpinner7.addChangeListener(new javax.swing.event.ChangeListener() {
//		public void stateChanged(javax.swing.event.ChangeEvent evt) {
//		    jSpinner1StateChanged(evt);
//		}
//	    });
//	    
//	    jSpinner8.addChangeListener(new javax.swing.event.ChangeListener() {
//		public void stateChanged(javax.swing.event.ChangeEvent evt) {
//		    jSpinner2StateChanged(evt);
//		}
//	    });
//	    
//	    jLabel7.setText("Horas");
//	    
//	    jLabel8.setText("Minutos");
//	    
//	    org.jdesktop.layout.GroupLayout panelHoraJuevesLayout = new org.jdesktop.layout.GroupLayout(panelHoraJueves);
//	    panelHoraJueves.setLayout(panelHoraJuevesLayout);
//	    panelHoraJuevesLayout.setHorizontalGroup(
//	    panelHoraJuevesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.LEADING, panelHoraJuevesLayout.createSequentialGroup()
//	    .addContainerGap()
//	    .add(jSpinner7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//	    .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(21, 21, 21)
//	    .add(jSpinner8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//	    .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addContainerGap(61, Short.MAX_VALUE))
//	    );
//	    panelHoraJuevesLayout.setVerticalGroup(
//	    panelHoraJuevesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.LEADING, panelHoraJuevesLayout.createSequentialGroup()
//	    .addContainerGap()
//	    .add(panelHoraJuevesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelHoraJuevesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//	    .add(jSpinner7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//	    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelHoraJuevesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//	    .add(jSpinner8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
//	    .addContainerGap())
//	    );
//	    panelHoras.add(panelHoraJueves);
//	    
//	    jSpinner9.addChangeListener(new javax.swing.event.ChangeListener() {
//		public void stateChanged(javax.swing.event.ChangeEvent evt) {
//		    jSpinner1StateChanged(evt);
//		}
//	    });
//	    
//	    jSpinner10.addChangeListener(new javax.swing.event.ChangeListener() {
//		public void stateChanged(javax.swing.event.ChangeEvent evt) {
//		    jSpinner2StateChanged(evt);
//		}
//	    });
//	    
//	    jLabel9.setText("Horas");
//	    
//	    jLabel10.setText("Minutos");
//	    
//	    org.jdesktop.layout.GroupLayout panelHoraViernesLayout = new org.jdesktop.layout.GroupLayout(panelHoraViernes);
//	    panelHoraViernes.setLayout(panelHoraViernesLayout);
//	    panelHoraViernesLayout.setHorizontalGroup(
//	    panelHoraViernesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.LEADING, panelHoraViernesLayout.createSequentialGroup()
//	    .addContainerGap()
//	    .add(jSpinner9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//	    .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(21, 21, 21)
//	    .add(jSpinner10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//	    .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addContainerGap(61, Short.MAX_VALUE))
//	    );
//	    panelHoraViernesLayout.setVerticalGroup(
//	    panelHoraViernesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.LEADING, panelHoraViernesLayout.createSequentialGroup()
//	    .addContainerGap()
//	    .add(panelHoraViernesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelHoraViernesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//	    .add(jSpinner9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//	    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelHoraViernesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//	    .add(jSpinner10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
//	    .addContainerGap())
//	    );
//	    panelHoras.add(panelHoraViernes);
//	    
//	    jSpinner11.addChangeListener(new javax.swing.event.ChangeListener() {
//		public void stateChanged(javax.swing.event.ChangeEvent evt) {
//		    jSpinner1StateChanged(evt);
//		}
//	    });
//	    
//	    jSpinner12.addChangeListener(new javax.swing.event.ChangeListener() {
//		public void stateChanged(javax.swing.event.ChangeEvent evt) {
//		    jSpinner2StateChanged(evt);
//		}
//	    });
//	    
//	    jLabel11.setText("Horas");
//	    
//	    jLabel12.setText("Minutos");
//	    
//	    org.jdesktop.layout.GroupLayout panelHoraSabadoLayout = new org.jdesktop.layout.GroupLayout(panelHoraSabado);
//	    panelHoraSabado.setLayout(panelHoraSabadoLayout);
//	    panelHoraSabadoLayout.setHorizontalGroup(
//	    panelHoraSabadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.LEADING, panelHoraSabadoLayout.createSequentialGroup()
//	    .addContainerGap()
//	    .add(jSpinner11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//	    .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(21, 21, 21)
//	    .add(jSpinner12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//	    .add(jLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addContainerGap(61, Short.MAX_VALUE))
//	    );
//	    panelHoraSabadoLayout.setVerticalGroup(
//	    panelHoraSabadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.LEADING, panelHoraSabadoLayout.createSequentialGroup()
//	    .addContainerGap()
//	    .add(panelHoraSabadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelHoraSabadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//	    .add(jSpinner11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(jLabel11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//	    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelHoraSabadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//	    .add(jSpinner12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(jLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
//	    .addContainerGap())
//	    );
//	    panelHoras.add(panelHoraSabado);
//	    
//	    jSpinner13.addChangeListener(new javax.swing.event.ChangeListener() {
//		public void stateChanged(javax.swing.event.ChangeEvent evt) {
//		    jSpinner1StateChanged(evt);
//		}
//	    });
//	    
//	    jSpinner14.addChangeListener(new javax.swing.event.ChangeListener() {
//		public void stateChanged(javax.swing.event.ChangeEvent evt) {
//		    jSpinner2StateChanged(evt);
//		}
//	    });
//	    
//	    jLabel13.setText("Horas");
//	    
//	    jLabel14.setText("Minutos");
//	    
//	    org.jdesktop.layout.GroupLayout panelHoraDomingoLayout = new org.jdesktop.layout.GroupLayout(panelHoraDomingo);
//	    panelHoraDomingo.setLayout(panelHoraDomingoLayout);
//	    panelHoraDomingoLayout.setHorizontalGroup(
//	    panelHoraDomingoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.LEADING, panelHoraDomingoLayout.createSequentialGroup()
//	    .addContainerGap()
//	    .add(jSpinner13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//	    .add(jLabel13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(21, 21, 21)
//	    .add(jSpinner14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//	    .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addContainerGap(61, Short.MAX_VALUE))
//	    );
//	    panelHoraDomingoLayout.setVerticalGroup(
//	    panelHoraDomingoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.LEADING, panelHoraDomingoLayout.createSequentialGroup()
//	    .addContainerGap()
//	    .add(panelHoraDomingoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelHoraDomingoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//	    .add(jSpinner13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(jLabel13, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//	    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelHoraDomingoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//	    .add(jSpinner14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
//	    .addContainerGap())
//	    );
//	    panelHoras.add(panelHoraDomingo);
//	    
//	    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
//	    this.setLayout(layout);
//	    layout.setHorizontalGroup(
//	    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(0, 418, Short.MAX_VALUE)
//	    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
//	    .addContainerGap()
//	    .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//	    .add(panelHoras, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 302, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//	    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//	    );
//	    layout.setVerticalGroup(
//	    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//	    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
//	    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//	    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
//	    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2)
//	    .add(panelHoras))
//	    .addContainerGap())
//	    );
//	}
//	// </editor-fold>
//	
//	
//	
//	private void checkLunesItemStateChanged(java.awt.event.ItemEvent evt) {
//// TODO add your handling code here:
//	    JCheckBox jc=(JCheckBox)evt.getSource();
//	    
//	    if (jc.isSelected()) {
//		((JPanel)panelesHoras.get(jc.getText())).setVisible(true);
//	    }else {
//		((JPanel)panelesHoras.get(jc.getText())).setVisible(false);
//	    }
//	}
//	
//	private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {
//// TODO add your handling code here:
//	    JSpinner jsh=(JSpinner)evt.getSource();
//	    if (((Integer)jsh.getValue()).intValue()==-1)
//		jsh.setValue(new Integer(0));
//	    if (((Integer)jsh.getValue()).intValue()==60)
//		jsh.setValue(new Integer(59));
//	}
//	
//	
//	public Dia[] getDiasSelec() {
//	    Dia[]ad=new Dia[7];
//	    
//	    for(int i=0;i<7;i++) {
//		ad[i]=null;
//		if (((JPanel)panelesHoras.get(dias[i])).isVisible() ) {
//		    Dia d=new Dia();
//		    d.setDia(i);
//		    d.setHora( ((Integer) ((JSpinner)((JPanel)panelesHoras.get(dias[i])).getComponent(0)).getValue()).intValue() );
//		    d.setMin( ((Integer) ((JSpinner)((JPanel)panelesHoras.get(dias[i])).getComponent(2)).getValue()).intValue() );
//		    ad[i]=d;
//		}
//	    }
//	    
//	    return ad;
//	}
//	
//	
//	private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {
//// TODO add your handling code here:
//	    JSpinner jsh=(JSpinner)evt.getSource();
//	    if (((Integer)jsh.getValue()).intValue()==-1)
//		jsh.setValue(new Integer(0));
//	    if (((Integer)jsh.getValue()).intValue()==24)
//		jsh.setValue(new Integer(23));
//	}
//	
//	public javax.swing.JCheckBox getCheckDomingo() {
//        return checkDomingo;
//    }
//
//    public javax.swing.JCheckBox getCheckJueves() {
//        return checkJueves;
//    }
//
//    public javax.swing.JCheckBox getCheckLunes() {
//        return checkLunes;
//    }
//
//    public javax.swing.JCheckBox getCheckMartes() {
//        return checkMartes;
//    }
//
//    public javax.swing.JCheckBox getCheckMiercoles() {
//        return checkMiercoles;
//    }
//
//    public javax.swing.JCheckBox getCheckSabado() {
//        return checkSabado;
//    }
//
//    public javax.swing.JCheckBox getCheckViernes() {
//        return checkViernes;
//    }
//	
//	
//	
//	// Variables declaration - do not modify
//	private javax.swing.JCheckBox checkDomingo;
//	private javax.swing.JCheckBox checkJueves;
//	private javax.swing.JCheckBox checkLunes;
//	private javax.swing.JCheckBox checkMartes;
//	private javax.swing.JCheckBox checkMiercoles;
//	private javax.swing.JCheckBox checkSabado;
//	private javax.swing.JCheckBox checkViernes;
//	private javax.swing.JLabel jLabel1;
//	private javax.swing.JLabel jLabel10;
//	private javax.swing.JLabel jLabel11;
//	private javax.swing.JLabel jLabel12;
//	private javax.swing.JLabel jLabel13;
//	private javax.swing.JLabel jLabel14;
//	private javax.swing.JLabel jLabel2;
//	private javax.swing.JLabel jLabel3;
//	private javax.swing.JLabel jLabel4;
//	private javax.swing.JLabel jLabel5;
//	private javax.swing.JLabel jLabel6;
//	private javax.swing.JLabel jLabel7;
//	private javax.swing.JLabel jLabel8;
//	private javax.swing.JLabel jLabel9;
//	private javax.swing.JPanel jPanel2;
//	private javax.swing.JSpinner jSpinner1;
//	private javax.swing.JSpinner jSpinner10;
//	private javax.swing.JSpinner jSpinner11;
//	private javax.swing.JSpinner jSpinner12;
//	private javax.swing.JSpinner jSpinner13;
//	private javax.swing.JSpinner jSpinner14;
//	private javax.swing.JSpinner jSpinner2;
//	private javax.swing.JSpinner jSpinner3;
//	private javax.swing.JSpinner jSpinner4;
//	private javax.swing.JSpinner jSpinner5;
//	private javax.swing.JSpinner jSpinner6;
//	private javax.swing.JSpinner jSpinner7;
//	private javax.swing.JSpinner jSpinner8;
//	private javax.swing.JSpinner jSpinner9;
//	private javax.swing.JPanel panelHoraDomingo;
//	private javax.swing.JPanel panelHoraJueves;
//	private javax.swing.JPanel panelHoraLunes;
//	private javax.swing.JPanel panelHoraMartes;
//	private javax.swing.JPanel panelHoraMiercoles;
//	private javax.swing.JPanel panelHoraSabado;
//	private javax.swing.JPanel panelHoraViernes;
//	private javax.swing.JPanel panelHoras;
//	// End of variables declaration
//	String[]dias={"Lunes","Martes","Miercoles","Jueves","Viernes","Sabado","Domingo"};
//	
//    }
    
    
    
    String[]dias={"Lunes","Martes","Miercoles","Jueves","Viernes","Sabado","Domingo"};
    /** Creates new form VDetallesTipo */
    public VDetallesTipo(JInternalFrame parent, boolean modal,Proyecto p) {
	
	super(new Frame(),modal);
	padre=parent;
	initComponents();
	proy=p;
	inicializar();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(screenSize.width/2-getSize().width/2, screenSize.height/2-getSize().height/2-50);
	
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        panelFondo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel1.setBackground(new java.awt.Color(216, 228, 198));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jRadioButton1.setBackground(new java.awt.Color(216, 228, 198));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Diario");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setEnabled(false);
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(216, 228, 198));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Semanal");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton2.setEnabled(false);
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });

        jRadioButton4.setBackground(new java.awt.Color(216, 228, 198));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Una sola vez");
        jRadioButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton4.setEnabled(false);
        jRadioButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton4ItemStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jRadioButton1)
                    .add(jRadioButton4)
                    .add(jRadioButton2))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(52, 52, 52)
                .add(jRadioButton1)
                .add(79, 79, 79)
                .add(jRadioButton2)
                .add(83, 83, 83)
                .add(jRadioButton4)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        panelFondo.setBackground(new java.awt.Color(216, 228, 198));
        org.jdesktop.layout.GroupLayout panelFondoLayout = new org.jdesktop.layout.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 431, Short.MAX_VALUE)
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 362, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(panelFondo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jButton1)
                        .add(224, 224, 224)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(panelFondo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 26, Short.MAX_VALUE)
                .add(jButton1)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
            
    public void inicializar() {
	switch( ((ProyectoAuto)proy).getTipoEnv() ) {
	    case ProyectoAuto.DIARIO:{
		jRadioButton1.setSelected(true);
		
		((JSpinner)((JPanel) ((JPanel)pdia.getComponent(0)).getComponent(1)).getComponent(0)).setValue( new Integer((((ProyectoAuto)proy).getDia(0)).getHora()) );
		((JSpinner)((JPanel) ((JPanel)pdia.getComponent(0)).getComponent(1)).getComponent(2)).setValue( new Integer((((ProyectoAuto)proy).getDia(0)).getMin()) );
		
	    }break;
	    
	 
	    
	    case ProyectoAuto.SEMANAL:{
		jRadioButton2.setSelected(true);
		
		for(int i=0;i<((ProyectoAuto)proy).getDias();i++) {
		    
		    switch ((((ProyectoAuto)proy).getDia(i)).getDia())
		    {
			    case 0: psem.getCheckLunes().setSelected(true); break;
			    case 1: psem.getCheckMartes().setSelected(true); break;
			    case 2: psem.getCheckMiercoles().setSelected(true); break;
			    case 3: psem.getCheckJueves().setSelected(true); break;
			    case 4: psem.getCheckViernes().setSelected(true); break;
			    case 5: psem.getCheckSabado().setSelected(true); break;
			    case 6: psem.getCheckDomingo().setSelected(true); break;
		    }
		    
		    JPanel c=((JPanel)panelesHoras.get(dias[ (((ProyectoAuto)proy).getDia(i)).getDia()]));
		    c.setVisible(true);
		    ((JSpinner)c.getComponent(0)).setValue( new Integer((((ProyectoAuto)proy).getDia(i)).getHora()) );
		    ((JSpinner)c.getComponent(2)).setValue( new Integer((((ProyectoAuto)proy).getDia(i)).getMin()) );
		}
	    }break;
	    
	    case ProyectoAuto.UNA_VEZ:{
		jRadioButton4.setSelected(true);
		((JCalendar)((JPanel)pun.getComponent(0)).getComponent(0)).getDayChooser().setDay(  ((Dia)((ProyectoAuto)proy).getDia(0)).getFecha().getDia()  );
		((JCalendar)((JPanel)pun.getComponent(0)).getComponent(0)).getMonthChooser().setMonth( ((Dia)((ProyectoAuto)proy).getDia(0)).getFecha().getMes()  );
		((JCalendar)((JPanel)pun.getComponent(0)).getComponent(0)).getYearChooser().setYear( ((Dia)((ProyectoAuto)proy).getDia(0)).getFecha().getAnyo()   );
		
		((JSpinner)((JPanel) ((JPanel)pun.getComponent(0)).getComponent(1)).getComponent(0)).setValue( new Integer(((Dia)((ProyectoAuto)proy).getDia(0)).getHora()) );
		((JSpinner)((JPanel) ((JPanel)pun.getComponent(0)).getComponent(1)).getComponent(2)).setValue( new Integer(((Dia)((ProyectoAuto)proy).getDia(0)).getMin()) );
	    }break;
	    
	}
	
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
	if(pdia!=null) {
	    
	    ((ProyectoAuto)proy).eliminarDias();
	  
	    Dia d=new Dia();
	    d.setDia(0);
	    d.setHora(pdia.getHora());
	    d.setMin(pdia.getMin());
	    ((ProyectoAuto)proy).setTipoEnv(ProyectoAuto.DIARIO);
	    ((ProyectoAuto)proy).anyadirDia(d);
	} else if(psem!=null) {
	    
	    ((ProyectoAuto)proy).eliminarDias();
	   
	    ((ProyectoAuto)proy).setTipoEnv(ProyectoAuto.SEMANAL);
	    Dia[]AD=psem.getDiasSelec();
	    for(int i=0;i<7;i++) {
		if (AD[i]!=null)
		    ((ProyectoAuto)proy).anyadirDia(AD[i]);
	    }
	
	} else if (pun!=null) {
	    ((ProyectoAuto)proy).eliminarDias();
	   
	    
	    ((ProyectoAuto)proy).setTipoEnv(ProyectoAuto.UNA_VEZ);
	    Dia d=new Dia();
	    d.setFecha(pun.obtenerFecha());
	    d.setHora(pun.obtenerHora()[0]);
	    d.setMin(pun.obtenerHora()[1]);
	    
	    d.setDia(d.getFecha().obtenerDiaSemana());
	    ((ProyectoAuto)proy).anyadirDia(d);
	    
	    
	}
	
	this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jRadioButton4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton4ItemStateChanged
// TODO add your handling code here:
	this.panelFondo.removeAll();
	if(pdia!=null) pdia=null;
	
	if(psem!=null) psem=null;
	if(pun!=null)  pun=null;
	
	pun=new PanelUnico();
	pun.setSize(450,360);
	
	panelFondo.add(pun,0);
	pun.setVisible(true);
	panelFondo.revalidate();
	this.repaint();
    }//GEN-LAST:event_jRadioButton4ItemStateChanged
    
    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
// TODO add your handling code here:
	this.panelFondo.removeAll();
	if(pdia!=null) pdia=null;
	
	if(psem!=null) psem=null;
	if(pun!=null)  pun=null;
	
	pdia=new PanelDiario();
	pdia.setSize(450,360);
	
	panelFondo.add(pdia,0);
	pdia.setVisible(true);
	panelFondo.revalidate();
	this.repaint();
    }//GEN-LAST:event_jRadioButton1ItemStateChanged
    
    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
// TODO add your handling code here:
	
	this.panelFondo.removeAll();
	if(pdia!=null) pdia=null;
	if(psem!=null) psem=null;
	if(pun!=null)  pun=null;
	
	
	psem=new PanelSemanal();
	psem.setSize(450,360);
	
	panelFondo.add(psem,0);
	psem.setVisible(true);
	panelFondo.revalidate();
	this.repaint();
    }//GEN-LAST:event_jRadioButton2ItemStateChanged
    
  
    
    private Hashtable panelesHoras;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables
    PanelSemanal psem;
    PanelDiario pdia;
    PanelUnico pun;
  
    Proyecto proy;
    JInternalFrame padre;
}
