/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */

package bgc.gui.wysiwyg.draganddrop;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.util.Vector;
import javax.swing.JColorChooser;
import javax.swing.JList;
import org.hsqldb.Collation;

/**
 * Dialogo de Cambio de tipo de Fuente
 * @author Campus-Telematika S.L.
 */
public class DialogoFont extends javax.swing.JDialog {
    
    /**
     * Vector de Fuentes del sistema
     */
    Vector vc;
    /**
     * Label
     */
    JLabelHermes label;
    /**
     * Creates new form DialogoFont
     * @param parent Ventana Padre
     * @param modal Si es modal o no
     * @param label JLabel con el texto a modificar
     */
    public DialogoFont(java.awt.Frame parent, boolean modal,JLabelHermes label) {
        super(parent, modal);
        String[] fonts = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
        vc = new Vector(fonts.length - 5);
        for(int i = 0; i < fonts.length; i++) {
            if(!fonts[i].equals("Dialog") && !fonts[i].equals("DialogInput") && !fonts[i].equals("Monospaced") && !fonts[i].equals("SansSerif") && !fonts[i].equals("Serif")) {
                vc.add(fonts[i]);
            }
        }
        initComponents();
        this.label=label;
        this.setSize(427, 300);
        jList1.setSelectedIndex(0);
        jList2.setSelectedIndex(0);
        jComboBox1.setSelectedIndex(3);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jList1 = new JList(vc);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Normal", "Negrita", "Cursiva" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jLabel1.setText("Tipo fuente");

        jLabel2.setText("Estilo");

        jLabel3.setText("Tama\u00f1o");

        jTextField1.setText("Texto de Prueba. 0 1 2 3 4 5 ");

        jLabel4.setText("Prueba");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "5", "8", "10", "12", "14", "16", "18", "20", "22", "24", "26", "30", "34", "40" }));

        jLabel5.setText("Color");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setToolTipText("Pulsa para eligir el color");
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(42, 42, 42)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .add(jLabel2))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(53, 53, 53)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel3)
                                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(layout.createSequentialGroup()
                                .add(25, 25, 25)
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(13, 13, 13))))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 166, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField1))
                .addContainerGap(76, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton2)
                .add(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(32, 32, 32)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1)
                    .add(jLabel2)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollPane1, 0, 0, Short.MAX_VALUE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel5)
                            .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(23, 23, 23)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Muestra el selector de color
     * @param evt Evento
     */
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
// TODO add your handling code here:
        JColorChooser dcolor=new JColorChooser(Color.black);
        
        jLabel6.setBackground(dcolor.showDialog(null,"Elige el color",jLabel6.getBackground()));
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * Cambia el cursor a normal
     * @param evt Evento
     */
    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
// TODO add your handling code here:
        jLabel6.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel6MouseExited

    /**
     * Cambia el cursor a mano
     * @param evt Evento
     */
    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
// TODO add your handling code here:
      jLabel6.setCursor(new Cursor(Cursor.HAND_CURSOR));
             
    }//GEN-LAST:event_jLabel6MouseEntered
    
    /**
     * Actualiza el ejemplo
     * @param evt Evento
     */
    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
// TODO add your handling code here:
        jTextField1.setFont(getFuente());
        jTextField1.setForeground(jLabel6.getBackground());
    }//GEN-LAST:event_jList1ValueChanged
    
    
    
    /**
     * Cierra el dialogo
     * @param evt Evento
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * Modifica la fuente
     * @param evt Evento
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        String s=label.getArea().getText();
        String h="";
        if (s.substring(s.lastIndexOf("<body>")+6).startsWith("\n    <font"))
        {
            int x=s.substring(s.lastIndexOf("<body>")+6).indexOf(">");
            int y=s.indexOf("<body>")+6;
            x+=y;
            for (int i=0;i<s.length();i++)
                if (!((i<=x)&&(i>=y)))
                        h+=s.charAt(i);
            h.replaceAll("</font>"," ");
         s=h;   
        }
        
        s=s.substring(0,s.lastIndexOf("<body>")+6)+" <font color='#"+getColorRGB(jLabel6.getBackground()) +"' face='"+getFontName()+"' style="+obtenerEstiloHTML(obtenerEstilo((String)jList2.getSelectedValue()))+" size="+getFontTam()+">"+s+"</font>";
        label.getArea().setText(s);
     
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * Retorna el Nombre de la fuente
     * @return Nombre de la fuente
     */
    public String getFontName(){return (String)jList1.getSelectedValue();}
    /**
     * Retorna el estilo de la fuente
     * @return estilo de la fuente
     */
    public String getFontEstilo(){return (String)jList2.getSelectedValue();}
    /**
     * Retorna el tamaño de la fuente
     * @return tamaño de la fuente
     */
    public int getFontTam(){return Integer.parseInt((String)jComboBox1.getSelectedItem());}
    
    /**
     * Da el Estilo en formato HTML
     * @param s numero del estilo
     * @return Estilo en formato HTML
     */
    public String obtenerEstiloHTML(int s) {
        
        
        if (s==Font.PLAIN)
            return "normal";
        if (s==Font.BOLD)
            return "bold";
        if (s==Font.ITALIC)
            return "italic";
        return "";
    }
    /**
     * Obtiene el Estilo
     * @param s Nombre del estilo
     * @return Numero del Estilo
     */
    public int obtenerEstilo(String s) {
        int estilo=0;
        if (s==null)
            estilo=Font.PLAIN;
        else{
            if (s.equals("Normal"))
                estilo=Font.PLAIN;
            else if (s.equals("Negrita"))
                estilo=Font.BOLD;
            else if (s.equals("Cursiva"))
                estilo=Font.ITALIC;
        }
        return estilo;
    }
    
    /**
     * Dado un color retorna un string en rgb
     * @param c Color a traducir
     * @return Texto en RGB
     */
    public String getColorRGB(Color c)
    {
           int r=c.getRed();
           int g=c.getGreen();
           int b=c.getBlue();
           String col="";
           if (r<10)
               col+="0";
           col+=Integer.toHexString(r);
           if (g<10)
               col+="0";
           col+=Integer.toHexString(g);
           if (b<10)
               col+="0";
           col+=Integer.toHexString(b);
           
           return col;
    }
    /**
     * Retorna la fuente
     * @return fuente
     */
    public Font getFuente() {
        return new Font(getFontName(),obtenerEstilo((String)jList2.getSelectedValue()),getFontTam());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * Boton Aceptar
     */
    private javax.swing.JButton jButton1;
    /**
     * Boton Cerrar
     */
    private javax.swing.JButton jButton2;
    /**
     * ComboBox de tamaños
     */
    private javax.swing.JComboBox jComboBox1;
    /**
     * label
     */
    private javax.swing.JLabel jLabel1;
    /**
     * label
     */
    private javax.swing.JLabel jLabel2;
    /**
     * label
     */
    private javax.swing.JLabel jLabel3;
    /**
     * label
     */
    private javax.swing.JLabel jLabel4;
    /**
     * label
     */
    private javax.swing.JLabel jLabel5;
    /**
     * label
     */
    private javax.swing.JLabel jLabel6;
    /**
     * Lista de nombre de fuentes
     */
    private javax.swing.JList jList1;
    /**
     * Lista con los Estilos
     */
    private javax.swing.JList jList2;
    /**
     * ScrollPanel
     */
    private javax.swing.JScrollPane jScrollPane1;
    /**
     * ScrollPanel
     */
    private javax.swing.JScrollPane jScrollPane2;
    /**
     * Texto de prueba
     */
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
