package bgc.gui.proy.abrir;
import bgc.negocio.Fecha;
import java.util.GregorianCalendar;
/**
 * La clase VCalendario proporciona la interfaz necesaria para albergar el panel
 * calendario que permite visualizar fechas.
 *
 * @author Campus - Telematika, S.L.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */
public class VCalendario extends javax.swing.JDialog {
    
     /**Panel con calendario grafico*/ 
    PanelCalendario panel;
    /** Crea un nuevo jDialog VCalendario */
    public VCalendario(java.awt.Frame parent, boolean modal,Fecha f) {
	super(parent, modal);
	initComponents();
	fecha=f;
        panel=new PanelCalendario(f,this);
        jLabel1.add(panel);
        panel.setLocation(5,70);
        panel.setSize(296, 296);
	GregorianCalendar c = new GregorianCalendar();
	c.set(fecha.getAnyo(),fecha.getMes(),fecha.getDia());
	this.panel.jCalendar1.setCalendar(c);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(100, 150, 225));
        jLabel1.setBackground(new java.awt.Color(216, 228, 198));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hermes/imagenes/proyecto/Calendario.png")));
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    /**Fecha a mostrar en el calendario*/
    Fecha fecha;
}
