package bgc.gui.gbd;
import bgc.gui.VContenedor;
import bgc.gui.inicio.VInicio;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.metal.MetalInternalFrameUI;
/**
 * La clase VAnyadir proporciona la interfaz necesaria para albergar el panel
 * que realiza el alta de clientes en la base de datos
 *
 * @author Campus - Telematika, S.L.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */
public class VAnyadir extends javax.swing.JInternalFrame {
    
   /**Panel que alberga la funcionalidad para añadir clientes a la base de datos*/
    PanelAnyadir panel;
    /**Ventana del Visor Gestor*/
    VVisorGestor padre;
     /** Crea un nuevo InternalFrame VAnyadir */
    public VAnyadir(VVisorGestor padre) {
        initComponents();
        ((MetalInternalFrameUI)this.getUI()).setNorthPane(null);
        botonCerrar=new JLabel(new ImageIcon(getClass().getResource("/hermes/imagenes/iconos_barra/icono_cerrar.png")));
        botonCerrar.setSize(20,20);
        botonCerrar.setLocation(970,33);
        botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
             public void mouseEntered(java.awt.event.MouseEvent evt) {
                 botonCerrarMouseEntered(evt);
             }
             public void mouseClicked(java.awt.event.MouseEvent evt){
                botonCerrarMouseClicked(evt);
             }
         });
         jLabel1.add(botonCerrar);
        
        
         this.padre=padre; 
        panel = new PanelAnyadir(this);
        this.panel.setLocation(60,130);
        this.setSize(1024,675);
        this.panel.setSize(759, 316);
        jLabel1.add(panel);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 228, 198));
        setBorder(null);
        jLabel1.setBackground(new java.awt.Color(216, 228, 198));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hermes/imagenes/gbd/AnadirCliente_fondo.png")));
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**Nos devuelve el VVisorGestor que es el padre de la Ventana Anyadir*/
    public VVisorGestor getPadre(){return padre;}
    /**Cambia el cursor a mano*/
    private void botonCerrarMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        botonCerrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
        /**Cierra la ventana añadir*/
      private void botonCerrarMouseClicked(java.awt.event.MouseEvent evt){
       
       this.getPadre().getPanelPadre().setSelectedFrame(this.getPadre());
       this.dispose();
         
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    /**Icono para cerrar la ventana*/
    javax.swing.JLabel botonCerrar;
  
}
