package bgc.gui.proy.nuevo;
import bgc.bd.GestorBD;
import bgc.gui.proy.nuevo.automatico.VNuevoProy3TipoEnv;
import bgc.negocio.Cliente;
import bgc.negocio.Fecha;
import bgc.negocio.Utilidades;
import bgc.negocio.proyecto.Proyecto;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
/**
 * La clase PanelNuevoProy3 ofrece la interfaz necesaria para determinar los
 * destinatarios del mailing
 *
 * @author Campus - Telematika, S.L.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */
public class PanelNuevoProy3 extends javax.swing.JPanel {
    /**Ventana contenedora de este panel*/
    VNuevoProy3 padre;
    /** Crea un nuevo panel PanelNuevoProy3*/
    public PanelNuevoProy3(Proyecto p,VNuevoProy3 padre) {
        proy = p;
        this.padre=padre;
        initComponents();
        PanelBuscar1 panelBuscar1 = new PanelBuscar1();
        panelBuscar1.setLocation(0,5);
        panelBuscar1.setSize(200, 320);
        this.jPanel1.add(panelBuscar1);
        this.validate();
        this.repaint();
        GestorBD gbd=new GestorBD();
        gbd.abrirBD();
        Vector v=gbd.obtenerListado();
        Vector v1=gbd.obtenerCampos();
        gbd.cerrarBD();
        Object[][]ao=new Object[v.size()][v1.size()];
        for (int i=0;i<v.size();i++) {
            Cliente c=(Cliente)v.elementAt(i);
            ao[i][0]=c.getNombre() ;
            ao[i][1]=c.getApellido();
            ao[i][2]=c.getSexo();
            ao[i][3]=c.getDireccion();
            ao[i][4]=c.getCP();
            ao[i][5]=c.getCiudad();
            ao[i][6]=c.getProvincia();
            ao[i][7]=c.getEmail();
            ao[i][8]=c.getTelefono();
            ao[i][9]=c.getMovil();
            ao[i][10]=Fecha.ordenarFecha(c.getFechaNac().toString());
            if (v1.size()>Cliente.numCamposFijos+1) {
                ao[i][Cliente.numCamposFijos+1]=c.getExtra1();
                if (v1.size()>Cliente.numCamposFijos+2) {
                    ao[i][Cliente.numCamposFijos+2]=c.getExtra2();
                    if (v1.size()>Cliente.numCamposFijos+3) {
                        ao[i][Cliente.numCamposFijos+3]=c.getExtra3();
                        if (v1.size()>Cliente.numCamposFijos+4) {
                            ao[i][Cliente.numCamposFijos+4]=c.getExtra4();
                            
                        }
                    }
                }
            }
        }
        jTableListado.getTableHeader().setFont(new Font("Arial",Font.BOLD,12));
        jTableListado.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableListado.setCellEditor(null);
        jTableListado.enableInputMethods(false);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        jTableListado.setAutoscrolls(true);
        jScrollPane1.setVerticalScrollBar(jScrollPane1.createVerticalScrollBar());
        String ArrayCampos[] = new String[v1.size()];
        for (int i=0; i<v1.size();i++) {
            ArrayCampos[i] = v1.elementAt(i).toString();
        }
        jTableListado.setModel(new javax.swing.table.DefaultTableModel(ao,ArrayCampos));
        jScrollPane1.setViewportView(jTableListado);
        sqlGuardar="";
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListado = new javax.swing.JTable();

        setBackground(new java.awt.Color(240, 240, 240));
        setOpaque(false);
        jPanel1.setBackground(new java.awt.Color(216, 228, 198));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criterios de b\u00fasqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12)));
        jPanel1.setOpaque(false);
        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 219, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 345, Short.MAX_VALUE)
        );

        jButton3.setBackground(new java.awt.Color(240, 240, 240));
        jButton3.setFont(new java.awt.Font("Arial", 0, 12));
        jButton3.setText("Siguiente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(240, 240, 240));
        jButton2.setFont(new java.awt.Font("Arial", 0, 12));
        jButton2.setText("Anterior");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(240, 240, 240));
        jButton4.setFont(new java.awt.Font("Arial", 0, 12));
        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(240, 240, 240));
        jButton5.setFont(new java.awt.Font("Arial", 0, 12));
        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(240, 240, 240));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Destinatarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12)));
        jScrollPane1.setOpaque(false);
        jTableListado.setBackground(new java.awt.Color(216, 228, 198));
        jTableListado.setFont(new java.awt.Font("Arial", 0, 10));
        jTableListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableListado.setGridColor(new java.awt.Color(0, 0, 0));
        jTableListado.setOpaque(false);
        jTableListado.setVerifyInputWhenFocusTarget(false);
        jTableListado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableListadoKeyPressed(evt);
            }
        });
        jTableListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableListadoMouseReleased(evt);
            }
        });

        jScrollPane1.setViewportView(jTableListado);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 346, Short.MAX_VALUE)
                .add(jButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton3))
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton2)
                    .add(jButton5)
                    .add(jButton4)))
        );
    }// </editor-fold>//GEN-END:initComponents
/**Permite que no se puedan editar las celdas al hacer doble clic*/
    private void jTableListadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListadoMouseReleased
// TODO add your handling code here:
        
         if (evt.getClickCount()>=2) {
            jTableListado.getCellEditor().stopCellEditing();
         }
        
    }//GEN-LAST:event_jTableListadoMouseReleased
/**Inicializa la búsqueda*/
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
        this.jPanel1.remove(0);
        PanelBuscar1 panelBuscar1 = new PanelBuscar1();
        panelBuscar1.setLocation(0,5);
        panelBuscar1.setSize(200, 320);
        this.jPanel1.add(panelBuscar1);
        this.validate();
        this.repaint();
        GestorBD gbd=new GestorBD();
        gbd.abrirBD();
        Vector v=gbd.obtenerListado();
        Vector v1=gbd.obtenerCampos();
        gbd.cerrarBD();
        Object[][]ao=new Object[v.size()][v1.size()];
        for (int i=0;i<v.size();i++) {
            Cliente c=(Cliente)v.elementAt(i);
            ao[i][0]=c.getNombre() ;
            ao[i][1]=c.getApellido();
            ao[i][2]=c.getSexo();
            ao[i][3]=c.getDireccion();
            ao[i][4]=c.getCP();
            ao[i][5]=c.getCiudad();
            ao[i][6]=c.getProvincia();
            ao[i][7]=c.getEmail();
            ao[i][8]=c.getTelefono();
            ao[i][9]=c.getMovil();
            ao[i][10]=c.getFechaNac().toString();
             if (v1.size()>Cliente.numCamposFijos+1) {
                ao[i][Cliente.numCamposFijos+1]=c.getExtra1();
                if (v1.size()>Cliente.numCamposFijos+2) {
                    ao[i][Cliente.numCamposFijos+2]=c.getExtra2();
                    if (v1.size()>Cliente.numCamposFijos+3) {
                        ao[i][Cliente.numCamposFijos+3]=c.getExtra3();
                        if (v1.size()>Cliente.numCamposFijos+4) {
                            ao[i][Cliente.numCamposFijos+4]=c.getExtra4();
                            
                        }
                    }
                }
            }
        }
        jTableListado.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableListado.setCellEditor(null);
        jTableListado.enableInputMethods(false);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        jTableListado.setAutoscrolls(true);
        jScrollPane1.setVerticalScrollBar(jScrollPane1.createVerticalScrollBar());
        String ArrayCampos[] = new String[v1.size()];
        for (int i=0; i<v1.size();i++) {
            ArrayCampos[i] = v1.elementAt(i).toString();
        }
        
       
        
        jTableListado.setModel(new javax.swing.table.DefaultTableModel(ao,ArrayCampos));
        jScrollPane1.setViewportView(jTableListado);
    }//GEN-LAST:event_jButton5ActionPerformed
/**Determina si se ha pulsado una tecla sobre la jTable*/
    private void jTableListadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableListadoKeyPressed
// TODO add your handling code here:
        evt.setKeyCode(KeyEvent.VK_LEFT);
    }//GEN-LAST:event_jTableListadoKeyPressed
   /**Devuelve un booleano indicando si hay seleccionados clientes o no en la jTable*/
    public boolean haySeleccionados() {
        for(int i=0;i<jTableListado.getRowCount();i++) {
            if (this.jTableListado.isRowSelected(i)) {
                return true;
            }
        }
        return false;
    }
  /**Devuelve los clientes seleccionados en un Vector*/
    public Vector getSeleccionados() {
        Vector A=new Vector(jTableListado.getRowCount());
        for(int i=0;i<jTableListado.getRowCount();i++) {
            if (this.jTableListado.isRowSelected(i)) {
                A.add(new Integer(i));
            }
        }
        return A;
    }
    /**Devuelve un string con la select necesaria para obtener los clientes
     determinados por los criterios de búsqueda */
    public String obtenerSelect(Vector v) {
        String s="Select * from Clientes where ";
        for (int i=0;i<v.size();i++) {
            int pos=((Integer)v.elementAt(i)).intValue();
            if (i==0) {
                s+="(nombre='"+(String)jTableListado.getValueAt(pos,0)+"' and apellidos ='"+(String)jTableListado.getValueAt(pos,1) +"' and email='"+(String)jTableListado.getValueAt(pos,7) +"')";
            } else {
                
                s+=" or (nombre='"+(String)jTableListado.getValueAt(pos,0)+"' and apellidos ='"+(String)jTableListado.getValueAt(pos,1) +"' and email='"+(String)jTableListado.getValueAt(pos,7) +"')";
            }
        }
        return s;
    }
     /**Lleva al siguiente paso dependiendo del tipo de envío y guarda los valores del proyecto actuales*/
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
        if (haySeleccionados()) {
            Vector vselec=getSeleccionados();
            sqlGuardar=obtenerSelect(vselec);
        } else if (sqlGuardar.equals("")) {
            sqlGuardar="select * from Clientes order by nombre";
        }
        proy.setSql(sqlGuardar);
        if (proy.getTipo().equals("Manual")){
            VNuevoProy4Manual v = new VNuevoProy4Manual(proy);
            this.padre.getParent().add(v);
            this.padre.dispose();
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2);
            v.show();
        }
        if (proy.getTipo().equals("Automatizado")){
            VNuevoProy3TipoEnv vnp=new VNuevoProy3TipoEnv(this.proy);
            this.padre.getParent().add(vnp);
            this.padre.dispose();
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            vnp.setLocation(screenSize.width/2-vnp.getSize().width/2, screenSize.height/2-vnp.getSize().height/2);
            vnp.show();
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed
    /**Realiza la búsqueda requerida por los criterios indicados*/
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
        String []ArraySql= new String [7];
        String sql="";
        GestorBD gbd=new GestorBD();
        gbd.abrirBD();
        
        if (jPanel1.getComponentCount()==1) {
            PanelBuscar1 panel = new PanelBuscar1();
            panel = (PanelBuscar1)this.jPanel1.getComponent(0);
           
            JTextField primero = new JTextField();
            primero = (JTextField)panel.getComponent(3);
            JTextField segundo = new JTextField();
            segundo = (JTextField)panel.getComponent(5);
            JComboBox combo = new JComboBox();
            combo = (JComboBox)panel.getComponent(0);
             ArraySql[0]=Utilidades.nombreCampoABD((String)combo.getSelectedItem());//break;
            ArraySql[1]=primero.getText();
            
            sql=((PanelBuscar1)this.jPanel1.getComponent(0)).obtenerSentencia();
            if (((JRadioButton)panel.getComponent(7)).isSelected() ) {
                sql=sql+" AND";
                sql=sql+((PanelBuscar2)((PanelBuscar1)this.jPanel1.getComponent(0)).getComponent(9)).obtenerSentencia();
            }else  if (((JRadioButton)panel.getComponent(8)).isSelected() ) {
                sql=sql+" OR";
                sql=sql+((PanelBuscar2)((PanelBuscar1)this.jPanel1.getComponent(0)).getComponent(9)).obtenerSentencia();
            }
            sql=sql+" order by "+ArraySql[0];
          
            
        }
        
        Vector aux=gbd.obtenerListado();
        
        
        Vector v=gbd.buscar(sql);
        sqlGuardar = (String)v.get(v.size()-1);
        cargarListadoBusqueda(v);
        gbd.cerrarBD();
        
    }//GEN-LAST:event_jButton4ActionPerformed
    /**Vuelve al paso anterior*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VNuevoProy2 v = new VNuevoProy2(proy);
        this.padre.getParent().add(v);
        this.padre.dispose();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2);
        v.show();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.ButtonGroup buttonGroup3;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableListado;
    // End of variables declaration//GEN-END:variables
    /**Variable para la información del proyecto en curso*/
    Proyecto proy;
     /**Variable para la sql resultado de los criterios de búsqueda*/
    String sqlGuardar;
    
    /**Carga los datos de los clientes resultados de una búsqueda que se pasan
     en el vector que se le pasa a la función*/
    public void cargarListadoBusqueda(Vector v) {
        v.remove(v.size()-1);
        GestorBD gbd=new GestorBD();
        gbd.abrirBD();
        
        Vector v1=gbd.obtenerCampos();
        gbd.cerrarBD();
        Object[][]ao=new Object[v.size()][v1.size()];
        for (int i=0;i<v.size();i++) {
            Cliente c=(Cliente)v.elementAt(i);
            ao[i][0]=c.getNombre() ;
            ao[i][1]=c.getApellido();
            ao[i][2]=c.getSexo();
            ao[i][3]=c.getDireccion();
            ao[i][4]=c.getCP();
            ao[i][5]=c.getCiudad();
            ao[i][6]=c.getProvincia();
            ao[i][7]=c.getEmail();
            ao[i][8]=c.getTelefono();
            ao[i][9]=c.getMovil();
            ao[i][10]=c.getFechaNac().toString();
             if (v1.size()>Cliente.numCamposFijos+1) {
                ao[i][Cliente.numCamposFijos+1]=c.getExtra1();
                if (v1.size()>Cliente.numCamposFijos+2) {
                    ao[i][Cliente.numCamposFijos+2]=c.getExtra2();
                    if (v1.size()>Cliente.numCamposFijos+3) {
                        ao[i][Cliente.numCamposFijos+3]=c.getExtra3();
                        if (v1.size()>Cliente.numCamposFijos+4) {
                            ao[i][Cliente.numCamposFijos+4]=c.getExtra4();
                            
                        }
                    }
                }
            }
        }
        jTableListado.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableListado.setCellEditor(null);
        jTableListado.enableInputMethods(false);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        jTableListado.setAutoscrolls(true);
        jScrollPane1.setVerticalScrollBar(jScrollPane1.createVerticalScrollBar());
        String ArrayCampos[] = new String[v1.size()];
        for (int i=0; i<v1.size();i++) {
            ArrayCampos[i] = v1.elementAt(i).toString();
        }
        
        jTableListado.setModel(new javax.swing.table.DefaultTableModel(ao,ArrayCampos));

        jScrollPane1.setViewportView(jTableListado);
    }
}
