package bgc.gui.proy.nuevo;
import bgc.gui.inicio.VInicio;
import bgc.gui.proy.nuevo.especial.VNuevoProy2Esp;
import bgc.negocio.Fecha;
import bgc.negocio.proyecto.Proyecto;
import bgc.negocio.proyecto.ProyectoAuto;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
/**
 * La clase PanelNuevoProy1 ofrece la interfaz necesaria para determinar el 
 * nombre, la descripción y el tipo de envío del mailing
 *
 * @author Campus - Telematika, S.L.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */
public class PanelNuevoProy1 extends javax.swing.JPanel {
    /**Variable para la información del proyecto en curso*/
    Proyecto p;
    /**Ventana contenedora de este panel*/
    VNuevoProy1 padre;
     /** Crea un nuevo panel PanelNuevoProy1*/
    public PanelNuevoProy1(Proyecto p,VNuevoProy1 padre) {
        initComponents();
        this.p=p;
        this.padre=padre;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 253, 252));
        setOpaque(false);
        jLabel1.setBackground(new java.awt.Color(216, 228, 198));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setText("Nombre");

        jLabel2.setBackground(new java.awt.Color(216, 228, 198));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel2.setText("Descripci\u00f3n");

        jTextField1.setBackground(new java.awt.Color(216, 228, 198));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 12));

        jTextArea1.setBackground(new java.awt.Color(216, 228, 198));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 12));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jRadioButton1.setBackground(new java.awt.Color(216, 228, 198));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 12));
        jRadioButton1.setText("Manual");
        jRadioButton1.setToolTipText("Env\u00edo manual");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton1.setOpaque(false);

        jRadioButton2.setBackground(new java.awt.Color(216, 228, 198));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 12));
        jRadioButton2.setText("Programado");
        jRadioButton2.setToolTipText("Env\u00edo automatizado");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton2.setOpaque(false);

        jRadioButton3.setBackground(new java.awt.Color(216, 228, 198));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Arial", 0, 12));
        jRadioButton3.setText("Especial");
        jRadioButton3.setToolTipText("Env\u00edo especial");
        jRadioButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton3.setOpaque(false);

        jButton1.setBackground(new java.awt.Color(240, 240, 240));
        jButton1.setFont(new java.awt.Font("Arial", 0, 12));
        jButton1.setText("Anterior");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed4(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(240, 240, 240));
        jButton3.setFont(new java.awt.Font("Arial", 0, 12));
        jButton3.setText("Siguiente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed4(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(216, 228, 198));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel3.setText("Tipo de env\u00edo");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2)
                            .add(jLabel3))
                        .add(16, 16, 16)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jRadioButton1)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .add(jRadioButton2)
                            .add(jRadioButton3))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(7, 7, 7)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jRadioButton1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButton3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 35, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton3)
                    .add(jButton1)))
        );
    }// </editor-fold>//GEN-END:initComponents
/**Vuelve a la ventana de inicio*/
    private void jButton1ActionPerformed4(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed4
// TODO add your handling code here:
       VInicio v = new VInicio();
       this.padre.getParent().add(v);
       this.padre.dispose();
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
       v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2);
       v.show();
    }//GEN-LAST:event_jButton1ActionPerformed4
/**Lleva al siguiente paso dependiendo del tipo de envío elegido y guarda los valores
 del proyecto actuales*/
    private void jButton3ActionPerformed4(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed4

// TODO add your handling code here:
        Date d = new Date();
        GregorianCalendar c = new GregorianCalendar();
        c.setTime(d);
        int dia = c.get(Calendar.DATE);
        int mes = c.get(Calendar.MONTH)+1;
        int anyo = c.get(Calendar.YEAR);
        String tipo="";
	Proyecto p = null;
       
        if (this.jRadioButton1.isSelected()){
             tipo = "Manual";
	      p= new Proyecto(this.jTextField1.getText(),this.jTextArea1.getText(),new Fecha(dia,mes,anyo),tipo,"","","");
            }
            if (this.jRadioButton2.isSelected()){
             tipo = "Automatizado";
	      p= new ProyectoAuto(this.jTextField1.getText(),this.jTextArea1.getText(),new Fecha(dia,mes,anyo),tipo,"","");
              ((ProyectoAuto)p).setFechaComienzo(p.getFecha());
              ((ProyectoAuto)p).setFechaFin(p.getFecha());
              
            }
            if (this.jRadioButton3.isSelected()){
            tipo = "Especial";
	     p= new ProyectoAuto(this.jTextField1.getText(),this.jTextArea1.getText(),new Fecha(dia,mes,anyo),tipo,"","");
            }
      
            
       if ((this.jRadioButton1.isSelected())&&(!this.jTextField1.getText().equals(""))){
             VNuevoProy2 v = new VNuevoProy2(p);
             this.padre.getParent().add(v);
             this.padre.dispose();
             Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
             v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2);
             v.show();
            }
            if ((this.jRadioButton2.isSelected())&&(!this.jTextField1.getText().equals(""))){
             VNuevoProy2 v = new VNuevoProy2(p);
             this.padre.getParent().add(v);
             this.padre.dispose();
             Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
             v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2);
             v.show();
            }
            if ((this.jRadioButton3.isSelected())&&(!this.jTextField1.getText().equals(""))){
             VNuevoProy2Esp v = new VNuevoProy2Esp(p);
             this.padre.getParent().add(v);
             this.padre.dispose();
             Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
             v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2);
             v.show();
            }
        
        if (this.jTextField1.getText().equals(""))
        {
            JOptionPane mensaje = new JOptionPane();
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            mensaje.setLocation(screenSize.width/2-mensaje.getSize().width/2, screenSize.height/2-mensaje.getSize().height/2);
            mensaje.showMessageDialog(this,"¡Debe elegir un nombre para el mailing!","Aviso",JOptionPane.WARNING_MESSAGE);
            
            
            return;
        }
        if ((!this.jRadioButton1.isSelected())&&(!this.jRadioButton2.isSelected())&&(!this.jRadioButton3.isSelected()))
        {
            JOptionPane mensaje = new JOptionPane();
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            mensaje.setLocation(screenSize.width/2-mensaje.getSize().width/2, screenSize.height/2-mensaje.getSize().height/2);
            
            mensaje.showMessageDialog(this,"¡Debe elegir un tipo de envío!","Aviso",JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_jButton3ActionPerformed4
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    javax.swing.JRadioButton jRadioButton1;
    javax.swing.JRadioButton jRadioButton2;
    javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTextArea jTextArea1;
    javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
