package bgc.gui.proy.nuevo;
import bgc.negocio.correo.HiloCorreo;
import bgc.negocio.correo.ResultadoEnvio;
import hermes.IconoSistema;
import java.awt.Image;
/**
 * La clase PanelProgreso ofrece la interfaz para ver el desarrollo
 * del envío del mailing
 *
 * @author Campus - Telematika, S.L.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */
public class PanelProgreso extends javax.swing.JPanel {
    /**Array con los resultado de los diferentes envíos*/
   ResultadoEnvio []as;
   /**Determina si ha finalizado el envío o no*/
   public boolean fin=false;
   /**Ventana que contiene a este panel*/
   VNuevoProyEnvio padre;
  /**Asunto del proyecto*/
  String titulo;
   /** Crea un nuevo jPanel PanelProgreso */
    public PanelProgreso(VNuevoProyEnvio v, ResultadoEnvio []as, String html,String titulo) {
	super();
        padre=v;
	initComponents();
	this.as=as;
	documentohtml=html;
        this.titulo=titulo;
    }
    /**Cierra el panel*/
    public void cerrar()
    {
      this.padre.eliminarProgreso();
      IconoSistema.cambiarIcono("/hermes/imagenes/iconos_barra/icono_barra.png");
      
    }
    /**Comienza el envio de mail*/
    public void func()
    {

        HiloCorreo hc=new HiloCorreo(as,fin,padre,this,documentohtml,titulo);
        hc.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        progreso = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 228, 198));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        progreso.setBackground(new java.awt.Color(216, 228, 198));

        jLabel1.setBackground(new java.awt.Color(240, 240, 240));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hermes/imagenes/iconos_barra/envio_progreso.gif")));
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(216, 228, 198));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel2.setText("Enviando");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .add(progreso, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .add(17, 17, 17)
                .add(progreso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JProgressBar progreso;
    // End of variables declaration//GEN-END:variables
    /**Icono que se muestra*/ 
    Image imagen;
    /**Documento html que se envia*/
     String documentohtml;
}
