package bgc.gui.proy.nuevo;
import bgc.gui.VContenedor;
import bgc.gui.inicio.VInicio;
import bgc.negocio.proyecto.Proyecto;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.metal.MetalInternalFrameUI;
/**
 * La clase VNuevoProy4Manual proporciona la interfaz necesaria para albergar el 
 * PanelNuevoProy4Manual
 *
 * @author Campus - Telematika, S.L.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */
public class VNuevoProy4Manual extends javax.swing.JInternalFrame {
    
   /**Panel que va a estar contenido en esta ventana*/
    PanelNuevoProy4Manual panel;
    /*Crea una nueva instancia del Internal Frame VNuevoProy4Manual*/
    public VNuevoProy4Manual(Proyecto p) {
	proy= p;
        initComponents();
        panel=new PanelNuevoProy4Manual(proy,this);
        jLabel1.add(panel);
        panel.setLocation(65,130);
        panel.setSize(936, 525);
        this.setSize(1024, 670);
        ((MetalInternalFrameUI)this.getUI()).setNorthPane(null);
	botonCerrar=new JLabel(new ImageIcon(getClass().getResource("/hermes/imagenes/iconos_barra/icono_cerrar.png")));
        botonCerrar.setSize(20,20);
        botonCerrar.setLocation(965,30);
         botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
             public void mouseEntered(java.awt.event.MouseEvent evt) {
                 botonCerrarMouseEntered(evt);
             }
             public void mouseClicked(java.awt.event.MouseEvent evt){
                botonCerrarMouseClicked(evt);
             }
             
         });
         jLabel1.add(botonCerrar);
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modfy this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 228, 198));
        setBorder(null);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hermes/imagenes/proyecto/NuevoProyecto04_fondo.png")));
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
  /**Cambia el cursor a mano*/
    private void botonCerrarMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        botonCerrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    /**Cierra la ventana VNuevoProy4Manual*/
    private void botonCerrarMouseClicked(java.awt.event.MouseEvent evt){
        
       VInicio v = new VInicio();
       this.getParent().add(v);
       this.dispose();
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
       v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2);
       v.show();
        
    }
    
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
// TODO add your handling code here:
	
	
    }//GEN-LAST:event_formInternalFrameActivated
    /**Vuelve a la ventana de inicio*/     
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
// TODO add your handling code here:
	VInicio v = new VInicio();
	this.getParent().add(v);
	this.dispose();
	Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
	v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2-50);
	v.show();
    }//GEN-LAST:event_formInternalFrameClosing
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
   /**Datos del proyecto en curso*/
    Proyecto proy;
   /**Icono para el boton cerrar*/
    javax.swing.JLabel botonCerrar;
   
}
