/*
* This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */

package bgc.gui.proy.nuevo.automatico;
import bgc.negocio.Fecha;
import bgc.negocio.proyecto.ProyectoAuto;
import java.util.GregorianCalendar;
import bgc.negocio.proyecto.Proyecto;

/**
 * Panel de visualizacion del calendario
 * @author Campus-Telematika S.L.
 */
public class PanelCalendario extends javax.swing.JPanel{
    
    /** Creates new form VCalendario */
    VCalendario padre;
    /**
     * Tipo de la fecha si es fecha de inicio o de fin.
     */
    int tipoFecha;
    /**
     * Crea un nuevo PanelCalendario
     * @param f Fecha a visualizar
     * @param padre Ventana padre
     * @param tf Si es Fecha de inicio o de fin
     */
    public PanelCalendario(Fecha f, VCalendario padre,int tf) {
	
	initComponents();
        this.padre=padre;
	fecha=f;
        tipoFecha=tf;
	GregorianCalendar c = new GregorianCalendar();
	c.set(fecha.getAnyo(),fecha.getMes(),fecha.getDia());
	this.jCalendar1.setCalendar(c);
	
    }
    
    /** This method is called from within the constructor to
     * inytialize the form.
     * WARnyNG: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(216, 228, 198));
        setOpaque(false);
        jPanel1.setBackground(new java.awt.Color(216, 228, 198));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setOpaque(false);
        jCalendar1.setBackground(new java.awt.Color(216, 228, 198));
        jCalendar1.setFont(new java.awt.Font("Arial", 0, 10));
        jCalendar1.setOpaque(false);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jCalendar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jCalendar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(240, 240, 240));
        jButton1.setFont(new java.awt.Font("Arial", 0, 10));
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .add(jButton1)
                .add(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Modifica la fecha
     * @param evt Evento
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        if (tipoFecha==0)
        {
        ((ProyectoAuto)this.padre.proyecto).setFechaComienzo(new Fecha(this.jCalendar1.getDayChooser().getDay(),this.jCalendar1.getMonthChooser().getMonth()+1,this.jCalendar1.getYearChooser().getYear()));
        }else
        {
        ((ProyectoAuto)this.padre.proyecto).setFechaFin(new Fecha(this.jCalendar1.getDayChooser().getDay(),this.jCalendar1.getMonthChooser().getMonth()+1,this.jCalendar1.getYearChooser().getYear()));
        }
        this.padre.dispose();
	
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * Boton aceptar
     */
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    /**
     * JCalendar
     */
    public com.toedter.calendar.JCalendar jCalendar1;
    /**
     * Panel
     */
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    /**
     * Fecha
     */
    Fecha fecha;
}
