/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */
package bgc.gui.proy.nuevo.automatico;
import bgc.gui.proy.abrir.PanelDiario;
import bgc.gui.proy.abrir.PanelUnico;
import bgc.gui.proy.automat.PanelSemanal;
import bgc.gui.proy.nuevo.*;
import bgc.negocio.Dia;
import bgc.negocio.Fecha;
import bgc.negocio.proyecto.Proyecto;
import bgc.negocio.proyecto.ProyectoAuto;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.util.Hashtable;
import javax.swing.JOptionPane;

/**
 * Muestra el tipo de envio a realizar
 * @author Campus-Telematika S.L.
 */
public class PanelTipoEnv extends javax.swing.JPanel{
    /**
     * Array con los nombres de los dias de la semana
     */
    String[]dias={"Lunes","Martes","Miercoles","Jueves","Viernes","Sabado","Domingo"};
    /**
     * Creates new form VNuevoProy3TipoEnv
     */
    VNuevoProy3TipoEnv padre;
    /**
     * Crea un nuevo PanelTipoEnvio
     * @param p Proyecto al que modificar el tipo envio
     * @param padre Ventana Padre
     */
    public PanelTipoEnv(Proyecto p,VNuevoProy3TipoEnv padre) {
        initComponents();
        proy=p;
        this.padre=padre;
        this.tFechaFin.setText(((ProyectoAuto)proy).getFechaComienzo().toString());
        this.tFechaIni.setText(((ProyectoAuto)proy).getFechaFin().toString());
        
        inicializar();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelFondo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tFechaIni = new javax.swing.JTextField();
        tFechaFin = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(216, 228, 198));
        setOpaque(false);
        jPanel1.setBackground(new java.awt.Color(216, 228, 198));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setOpaque(false);
        jRadioButton1.setBackground(new java.awt.Color(216, 228, 198));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 1, 12));
        jRadioButton1.setText("Diario");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton1.setOpaque(false);
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(216, 228, 198));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 1, 12));
        jRadioButton2.setText("Semanal");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton2.setOpaque(false);
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });

        jRadioButton4.setBackground(new java.awt.Color(216, 228, 198));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Arial", 1, 12));
        jRadioButton4.setText("Una sola vez");
        jRadioButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton4.setOpaque(false);
        jRadioButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton4ItemStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jRadioButton1)
                    .add(jRadioButton2)
                    .add(jRadioButton4))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jRadioButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButton4))
        );

        jButton1.setBackground(new java.awt.Color(240, 240, 240));
        jButton1.setFont(new java.awt.Font("Arial", 0, 10));
        jButton1.setText("Anterior");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(240, 240, 240));
        jButton2.setFont(new java.awt.Font("Arial", 0, 10));
        jButton2.setText("Siguiente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        panelFondo.setBackground(new java.awt.Color(216, 228, 198));
        panelFondo.setOpaque(false);
        org.jdesktop.layout.GroupLayout panelFondoLayout = new org.jdesktop.layout.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 416, Short.MAX_VALUE)
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 337, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(216, 228, 198));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setOpaque(false);
        jLabel1.setBackground(new java.awt.Color(216, 228, 198));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setText("Fecha Comienzo");

        jLabel2.setBackground(new java.awt.Color(216, 228, 198));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel2.setText("Fecha Fin");

        tFechaIni.setFont(new java.awt.Font("Arial", 0, 10));

        tFechaFin.setFont(new java.awt.Font("Arial", 0, 10));

        jButton4.setBackground(new java.awt.Color(216, 228, 198));
        jButton4.setFont(new java.awt.Font("Arial", 0, 10));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hermes/imagenes/automat/icono_calendario.gif")));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(216, 228, 198));
        jButton5.setFont(new java.awt.Font("Arial", 0, 10));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hermes/imagenes/automat/icono_calendario.gif")));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel2Layout.createSequentialGroup()
                            .add(tFechaIni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(tFechaFin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tFechaIni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tFechaFin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(panelFondo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(panelFondo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jButton2)
                            .add(jButton1)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Muestra la ventana de calendario
     * @param evt Evento
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
        VCalendario v=new VCalendario(new Frame(),true,proy,1);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        v.setLocation(400,300);
        
        v.setTitle("Fecha fin envío");
        v.show();
        actualizar();
    }//GEN-LAST:event_jButton5ActionPerformed
    
    /**
     * Muestra la ventana de calendario
     * @param evt Evento
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
        VCalendario v=new VCalendario(new Frame(),true,proy,0);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        v.setLocation(400, 300);
        
        v.setTitle("Fecha inicio envío");
        v.show();
        actualizar();
    }//GEN-LAST:event_jButton4ActionPerformed
    
    /**
     * Comprueba los diferentes paneles posibles, para modificar el proyecto con la 
     * periocidad estipulado por el usuario. 
     * Despues muetra la siguiente Ventana
     * @param evt Evento
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        if ((!this.jRadioButton1.isSelected())&&(!this.jRadioButton2.isSelected())&&(!this.jRadioButton4.isSelected())) {
            JOptionPane.showMessageDialog(this,"¡Debe elegir la periodicidad con la que desea realizar el envío!","Aviso",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(pdia!=null) {
            ((ProyectoAuto)proy).eliminarDias();
            Dia d=new Dia();
            d.setDia(0);
            d.setHora(pdia.getHora());
            d.setMin(pdia.getMin());
            ((ProyectoAuto)proy).setTipoEnv(ProyectoAuto.DIARIO);
            ((ProyectoAuto)proy).anyadirDia(d);
        } else if(psem!=null) {
            ((ProyectoAuto)proy).eliminarDias();
            ((ProyectoAuto)proy).setTipoEnv(ProyectoAuto.SEMANAL);
            Dia[]AD=psem.getDiasSelec();
            for(int i=0;i<7;i++) {
                if (AD[i]!=null)
                    ((ProyectoAuto)proy).anyadirDia(AD[i]);
            }
            if ((psem.getCheckLunes().isSelected()==false)&&(psem.getCheckMartes().isSelected()==false)&&(psem.getCheckMiercoles().isSelected()==false)&&(psem.getCheckJueves().isSelected()==false)&&(psem.getCheckViernes().isSelected()==false)&&(psem.getCheckSabado().isSelected()==false)&&(psem.getCheckDomingo().isSelected()==false)) {
                JOptionPane.showMessageDialog(this,"¡Debe elegir al menos un día de la semana!","Aviso",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }  else if (pun!=null) {
            ((ProyectoAuto)proy).eliminarDias();
            ((ProyectoAuto)proy).setTipoEnv(ProyectoAuto.UNA_VEZ);
            Dia d=new Dia();
            d.setFecha(pun.obtenerFecha());
            d.setHora(pun.obtenerHora()[0]);
            d.setMin(pun.obtenerHora()[1]);
          
            d.setDia(d.getFecha().obtenerDiaSemana());
            ((ProyectoAuto)proy).anyadirDia(d);
        }
        VFinalizar v = new VFinalizar(proy);
        this.padre.getParent().add(v);
        this.padre.dispose();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2);
        v.show();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * Volver  a la ventana anterior
     * @param evt Evento
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        VNuevoProy3 v = new VNuevoProy3(proy);
        this.padre.getParent().add(v);
        this.padre.dispose();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2);
        v.show();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * Carga en pantalla el panel de seleccion de un solo envio
     * @param evt Evento
     */
    private void jRadioButton4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton4ItemStateChanged
// TODO add your handling code here:
        this.panelFondo.removeAll();
        if(pdia!=null) pdia=null;
        if(psem!=null) psem=null;
        if(pun!=null)  pun=null;
        pun=new PanelUnico();
        
        pun.setSize(235, 293);
        pun.setLocation(0,10);
        panelFondo.add(pun,0);
        pun.setVisible(true);
        this.jPanel2.setVisible(false);
        panelFondo.revalidate();
        this.repaint();
    }//GEN-LAST:event_jRadioButton4ItemStateChanged
    
    /**
     * Carga en pantalla el panel de seleccion diaria
     * @param evt Evento
     */
    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
// TODO add your handling code here:
        this.panelFondo.removeAll();
        if(pdia!=null) pdia=null;
        if(psem!=null) psem=null;
        if(pun!=null)  pun=null;
        pdia=new PanelDiario();
        pdia.setSize(333, 88);
        panelFondo.add(pdia,0);
        pdia.setLocation(0,10);
        pdia.setVisible(true);
        this.jPanel2.setVisible(true);
        panelFondo.revalidate();
        this.repaint();
    }//GEN-LAST:event_jRadioButton1ItemStateChanged
    
    /**
     * Carga en pantalla el panel de seleccion semanal
     * @param evt Evento
     */
    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
// TODO add your handling code here:
        this.panelFondo.removeAll();
        if(pdia!=null) pdia=null;
        if(psem!=null) psem=null;
        if(pun!=null)  pun=null;
        psem=new PanelSemanal();
        psem.setSize(440,340);
        psem.setLocation(0,0);
        panelFondo.add(psem,0);
        this.jPanel2.setVisible(true);
        this.jPanel2.setBackground(new Color(255,255,255));
        psem.setVisible(true);
        panelFondo.revalidate();
        this.repaint();
    }//GEN-LAST:event_jRadioButton2ItemStateChanged
    
    /**
     * Actualiza las fecha de inicio y fin
     */
    public void actualizar() {
        this.tFechaIni.setText(((ProyectoAuto)proy).getFechaComienzo().toString());
        this.tFechaFin.setText(((ProyectoAuto)proy).getFechaFin().toString());
        
        Fecha fechaInicio = Fecha.parse(tFechaIni.getText());
        
        Fecha fechaFin = Fecha.parse(tFechaFin.getText());
        
        
        if (fechaInicio.comparar(fechaFin)==0) {
            JOptionPane.showMessageDialog(this,"¡La fecha de inicio no puede ser igual que la fecha de fin!","Aviso",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (fechaInicio.comparar(fechaFin)==1) {
            JOptionPane.showMessageDialog(this,"¡La fecha de inicio no puede ser mayor que la fecha de fin!","Aviso",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
    }
    
    /**
     * Inicializa los componentes del panel
     */
    public void inicializar() {
        switch( ((ProyectoAuto)proy).getTipoEnv() ) {
            case ProyectoAuto.DIARIO:{
                 pdia=new bgc.gui.proy.abrir.PanelDiario();
                pdia.setSize(416, 337);
                pdia.setLocation(0,0);
                panelFondo.add(pdia);
                jRadioButton1.setSelected(true);
                
//////                    pdia.setHora((((ProyectoAuto)proy).getDia(0)).getHora());
//////                    pdia.setMin((((ProyectoAuto)proy).getDia(0)).getMin());
         
                
            }break;
            
            case ProyectoAuto.MENSUAL:{
                
            }break;
            
            case ProyectoAuto.SEMANAL:{
                jRadioButton2.setSelected(true);
                psem=new PanelSemanal();
                psem.setSize(416, 337);
                psem.setLocation(0,0);
                panelFondo.add(psem);
                
                for(int i=0;i<((ProyectoAuto)proy).getDias();i++) {
                    
                    switch ((((ProyectoAuto)proy).getDia(i)).getDia()) {
                        case 0: psem.marcarLunes(((ProyectoAuto)proy).getDia(i).getHora(),((ProyectoAuto)proy).getDia(i).getMin()); break;
                        case 1: psem.marcarMartes(((ProyectoAuto)proy).getDia(i).getHora(),((ProyectoAuto)proy).getDia(i).getMin());break;
                        case 2: psem.marcarMiercoles(((ProyectoAuto)proy).getDia(i).getHora(),((ProyectoAuto)proy).getDia(i).getMin()); break;
                        case 3: psem.marcarJueves(((ProyectoAuto)proy).getDia(i).getHora(),((ProyectoAuto)proy).getDia(i).getMin()); break;
                        case 4: psem.marcarViernes(((ProyectoAuto)proy).getDia(i).getHora(),((ProyectoAuto)proy).getDia(i).getMin()); break;
                        case 5: psem.marcarSabado(((ProyectoAuto)proy).getDia(i).getHora(),((ProyectoAuto)proy).getDia(i).getMin()); break;
                        case 6: psem.marcarDomingo(((ProyectoAuto)proy).getDia(i).getHora(),((ProyectoAuto)proy).getDia(i).getMin()); break;
                    }
                    
//                    ((JPanel)psem.panelesHoras.get(dias[ (((ProyectoAuto)proy).getDia(i)).getDia()])).setVisible(true);
//                   
//                    ((JSpinner)((JPanel)psem.panelesHoras.get(dias[ (((ProyectoAuto)proy).getDia(i)).getDia()])).getComponent(0)).setValue( new Integer((((ProyectoAuto)proy).getDia(i)).getHora()) );
//                    ((JSpinner)((JPanel)psem.panelesHoras.get(dias[ (((ProyectoAuto)proy).getDia(i)).getDia()])).getComponent(2)).setValue( new Integer((((ProyectoAuto)proy).getDia(i)).getMin()) );
//                    ((JPanel)psem.panelesHoras.get(dias[ (((ProyectoAuto)proy).getDia(i)).getDia()])).validate();
//                    ((JPanel)psem.panelesHoras.get(dias[ (((ProyectoAuto)proy).getDia(i)).getDia()])).repaint();
                    psem.validate();
                    psem.repaint();
                }
            }break;
            
            case ProyectoAuto.UNA_VEZ:{
                pun=new bgc.gui.proy.abrir.PanelUnico();
                pun.setSize(416, 337);
                pun.setLocation(0,0);
                panelFondo.add(pun);
                jRadioButton4.setSelected(true);
                
////                pun.setFecha(((Dia)((ProyectoAuto)proy).getDia(0)).getFecha().getDia(),((Dia)((ProyectoAuto)proy).getDia(0)).getFecha().getMes(),((Dia)((ProyectoAuto)proy).getDia(0)).getFecha().getAnyo());
////                pun.setHora(((Dia)((ProyectoAuto)proy).getDia(0)).getHora());
////                pun.setMin(((Dia)((ProyectoAuto)proy).getDia(0)).getMin());
                
               
            }break;
            
        }
        this.validate();
        this.repaint();
    }
    /**
     * Tabla de mapeo con los paneles de selección semanal
     */
    private Hashtable panelesHoras;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JRadioButton jRadioButton1;
    public javax.swing.JRadioButton jRadioButton2;
    public javax.swing.JRadioButton jRadioButton4;
    public javax.swing.JPanel panelFondo;
    public javax.swing.JTextField tFechaFin;
    public javax.swing.JTextField tFechaIni;
    // End of variables declaration//GEN-END:variables
    PanelSemanal psem;
    PanelDiario pdia;
    PanelUnico pun;
    Proyecto proy;
}
