/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */

package bgc.gui.proy.nuevo.automatico;
import bgc.negocio.Fecha;
import bgc.negocio.proyecto.Proyecto;
import java.util.GregorianCalendar;

/**
 * Ventana donde se mostrara un calendario
 * @author Campus-Telematika S.L.
 */
public class VCalendario extends javax.swing.JDialog {
    
    /** Creates new form VCalendario */
    PanelCalendario panel;
    Proyecto proyecto;
    /**
     * Crea una nueva Ventana calendario
     * @param parent Padre
     * @param modal si es modal o no
     * @param p Proyecto 
     * @param tf Tipo de fecha 
     */
    public VCalendario(java.awt.Frame parent, boolean modal,Proyecto p,int tf) {
	super(parent, modal);
	initComponents();
        this.setSize(310, 295);
	proyecto=p;
        panel=new PanelCalendario(proyecto.getFecha(),this,tf);
        this.add(panel);
        panel.setLocation(5,70);
        panel.setSize(308, 260);
        
	GregorianCalendar c = new GregorianCalendar();
	c.set(proyecto.getFecha().getAnyo(),proyecto.getFecha().getMes()-1,proyecto.getFecha().getDia());
	this.panel.jCalendar1.setCalendar(c);
        
	
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(216, 228, 198));
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Fecha a visualizar
     */
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    Fecha fecha;
}
