/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */

package bgc.gui.proy.nuevo.automatico;
import bgc.gui.VContenedor;
import bgc.gui.inicio.VInicio;
import bgc.negocio.proyecto.Proyecto;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.metal.MetalInternalFrameUI;/**
 * Ventana de resumen del mailing
 * @author Campus-Telematika S.L.
 */public class VFinalizar extends javax.swing.JInternalFrame {
     
     /**
      * Creates new form VFinalizar
      */
     PanelFinalizar panel;
     
    /**
     * Crea una nueva VFinalizar
     * @param p Proyecto
     */
     public VFinalizar(Proyecto p) {
	proy= p;
        initComponents();
        panel=new PanelFinalizar(proy,this);
        jLabel1.add(panel);
        panel.setLocation(60,120);
        panel.setSize(930, 520);
        this.setSize(1024, 670);
        ((MetalInternalFrameUI)this.getUI()).setNorthPane(null);
	botonCerrar=new JLabel(new ImageIcon(getClass().getResource("/hermes/imagenes/iconos_barra/icono_cerrar.png")));
         botonCerrar.setSize(20,20);
         botonCerrar.setLocation(965,30);
         botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
             public void mouseEntered(java.awt.event.MouseEvent evt) {
                 botonCerrarMouseEntered(evt);
             }
             public void mouseClicked(java.awt.event.MouseEvent evt){
                botonCerrarMouseClicked(evt);
             }
             
         });
         jLabel1.add(botonCerrar);
      botonAyuda=new JLabel(new ImageIcon(getClass().getResource("/hermes/imagenes/iconos_barra/icono_ayuda.png")));
         botonAyuda.setSize(20,20);
         botonAyuda.setLocation(945,30);
         botonAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
             public void mouseEntered(java.awt.event.MouseEvent evt) {
                 botonAyudaMouseEntered(evt);
             }
             public void mouseClicked(java.awt.event.MouseEvent evt){
                botonAyudaMouseClicked(evt);
             }
         });
         jLabel1.add(botonAyuda);
     }
	 
     
     
     /** This method is called from within the constructor to
      * initialize the form.
      * WARNING: Do NOT modfy this code. The content of this method is
      * always regenerated by the Form Editor.
      */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 228, 198));
        setBorder(null);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hermes/imagenes/proyecto/NuevoProyecto_ultimo_fondo.png")));
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Cambia el cursor a Mano
     * @param evt Evento
     */
    private void botonCerrarMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        botonCerrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    
    /**
     * Cierra la Ventana
     * @param evt Evento
     */
    private void botonCerrarMouseClicked(java.awt.event.MouseEvent evt){
        
       VInicio v = new VInicio();
       this.getParent().add(v);
       this.dispose();
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
       v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2);
       v.show();
        
    }            
    /**
     * Cambia el cursor a Mano
     * @param evt Evento
     */
     private void botonAyudaMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        botonCerrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    /**
     * Muestra la ayuda
     * @param evt Evento
     */
     private void botonAyudaMouseClicked(java.awt.event.MouseEvent evt){
        Object []botones={"Salir","Minimizar"};
        if(JOptionPane.showOptionDialog(null,"¿Desea salir o minimizar la aplicación?","Confirmación de salida",JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE,null,botones,botones[0])==JOptionPane.OK_OPTION) {
            this.dispose();
            System.exit(0);
        }else {
            ((VContenedor)this.getParent().getParent().getParent().getParent().getParent()).hide();
        }
    }
    /**
     * 
     * @param evt 
     */
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
// TODO add your handling code here:
	VInicio v = new VInicio();
	this.getParent().add(v);
	this.dispose();
	Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
	v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2-50);
	v.show();
    }//GEN-LAST:event_formInternalFrameClosing
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    javax.swing.JLabel botonCerrar;
    Proyecto proy;
     javax.swing.JLabel botonAyuda;
    
 }
