/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */

package bgc.gui.proy.nuevo.automatico;

import bgc.gui.VContenedor;
import bgc.gui.inicio.VInicio;
import bgc.gui.proy.abrir.PanelDiario;

import bgc.gui.proy.abrir.PanelUnico;
import bgc.negocio.proyecto.Proyecto;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Hashtable;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.metal.MetalInternalFrameUI;

/**
 * Ventana donde se muestra la seleccion del tipo de envio
 * @author Campus-Telematika S.L.
 */
public class VNuevoProy3TipoEnv extends javax.swing.JInternalFrame {
    
    /**
     * Array con los nombres de los dias de la semana
     */
    String[]dias={"Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"};
    /**
     * Creates new form VNuevoProy3TipoEnv
     */
    PanelTipoEnv panel;
    /**
     * Crea una nueva Ventana de VNuevoProy3TipoENv
     * @param p Proyecto
     */
    public VNuevoProy3TipoEnv(Proyecto p) {
	
	initComponents();
	proy=p;
        panel=new PanelTipoEnv(proy,this);
	
        ((MetalInternalFrameUI)this.getUI()).setNorthPane(null);
        panel.setSize(575,375);
        panel.setLocation(55,120);
        jLabel1.add(panel);
        this.setSize(1024, 670);
        botonCerrar=new JLabel(new ImageIcon(getClass().getResource("/hermes/imagenes/iconos_barra/icono_cerrar.png")));
        botonCerrar.setSize(20,20);
         botonCerrar.setLocation(965,30);
         botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
             public void mouseEntered(java.awt.event.MouseEvent evt) {
                 botonCerrarMouseEntered(evt);
             }
             public void mouseClicked(java.awt.event.MouseEvent evt){
                botonCerrarMouseClicked(evt);
             }
             
         });
         jLabel1.add(botonCerrar);
         botonAyuda=new JLabel(new ImageIcon(getClass().getResource("/hermes/imagenes/iconos_barra/icono_ayuda.png")));
         botonAyuda.setSize(20,20);
         botonAyuda.setLocation(945,30);
         botonAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
             public void mouseEntered(java.awt.event.MouseEvent evt) {
                 botonAyudaMouseEntered(evt);
             }
             public void mouseClicked(java.awt.event.MouseEvent evt){
                botonAyudaMouseClicked(evt);
             }
         });
         jLabel1.add(botonAyuda);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 228, 198));
        setBorder(null);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hermes/imagenes/proyecto/NuevoProyecto_periodicidad.png")));
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     /**
     * Cambia el cursor a mano
     * @param evt Evento
     */
       private void botonCerrarMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        botonCerrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    
    /**
     * Cierra la ventana
     * @param evt Evento
     */
    private void botonCerrarMouseClicked(java.awt.event.MouseEvent evt){
        
       VInicio v = new VInicio();
       this.getParent().add(v);
       this.dispose();
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
       v.setLocation(screenSize.width/2-v.getSize().width/2, screenSize.height/2-v.getSize().height/2);
       v.show();
        
    }        
    /**
     * Cambia el cursor a mano
     * @param evt Evento
     */
     private void botonAyudaMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        botonCerrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    /**
     * Muetra la ayuda
     * @param evt Evento
     */
     private void botonAyudaMouseClicked(java.awt.event.MouseEvent evt){
        Object []botones={"Salir","Minimizar"};
        if(JOptionPane.showOptionDialog(null,"¿Desea salir o minimizar la aplicación?","Confirmación de salida",JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE,null,botones,botones[0])==JOptionPane.OK_OPTION) {
            this.dispose();
            System.exit(0);
        }else {
            ((VContenedor)this.getParent().getParent().getParent().getParent().getParent()).hide();
        }
    }
    /**
     * Tabla de mapeo con los paneles de selección semanal
     */
    
    private Hashtable panelesHoras;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * 
     */
    private javax.swing.ButtonGroup buttonGroup1;
    /**
     * LAbel
     */
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
//    PanelSemanal psem;
//    PanelDiario pdia;
//    PanelUnico pun;
    
    /**
     * Proyecto del mailing en curso
     */
    Proyecto proy;
    /**
     * Boton
     */
     javax.swing.JLabel botonCerrar;
    /**
     * Boton
     */
     javax.swing.JLabel botonAyuda;
}

