/*
 * PanelFondo.java
 *
 * Created on 3 de febrero de 2006, 9:30
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */

package bgc.asistente;

import javax.swing.JOptionPane;

/**
 * Panel con el 3º paso del asistente
 * @author Campus-Telematika S.L
 */
public class Panel2 extends javax.swing.JPanel {
    
    /** Creates new form PanelFondo */
    InformacionInstalacion instalar;
    /**
     * Crea el Panel2
     * @param inst Informacion de la instalacion 
     */
    public Panel2(InformacionInstalacion inst) {
        initComponents();
        instalar=inst;
        actualizarListado();
        jLabel1.setText("Puedes añadir "+(4-instalar.getNumcamposOp())+" campos más");
        if (instalar.getNumeroCampos()==15) {
            jButton4.setEnabled(false);
            
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        textoNC = new javax.swing.JTextField();
        tipoDato = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jList1 = new java.awt.List();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 218, 185));
        setOpaque(false);
        jPanel1.setOpaque(false);
        jPanel2.setOpaque(false);
        textoNC.setBackground(new java.awt.Color(230, 237, 220));
        textoNC.setFont(new java.awt.Font("Arial", 0, 12));

        tipoDato.setBackground(new java.awt.Color(230, 237, 220));
        tipoDato.setFont(new java.awt.Font("Arial", 0, 12));
        tipoDato.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Texto", "Numero", "Fecha", "Si/No" }));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel7.setText("Nombre campo:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel8.setText("Tipo de dato: ");

        jButton4.setBackground(new java.awt.Color(240, 240, 240));
        jButton4.setFont(new java.awt.Font("Arial", 0, 12));
        jButton4.setText("A\u00f1adir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel8))
                                .add(14, 14, 14)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(textoNC, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, tipoDato, 0, 142, Short.MAX_VALUE)))
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(127, 127, 127)
                        .add(jButton4)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(textoNC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(20, 20, 20)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(tipoDato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 57, Short.MAX_VALUE)
                .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jList1.setBackground(new java.awt.Color(230, 237, 220));
        jList1.setFont(new java.awt.Font("Arial", 0, 12));

        jButton1.setBackground(new java.awt.Color(240, 240, 240));
        jButton1.setFont(new java.awt.Font("Arial", 0, 12));
        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jList1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(34, 34, 34)
                        .add(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jList1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel2.setForeground(new java.awt.Color(0, 50, 200));
        jLabel2.setText("Configuraci\u00f3n y creaci\u00f3n de la base de datos");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    /**
     * Retorna si el Campo es un nombre valido o no
     * @return Verifica si el campo es valido o no
     *    true  - es valido
     *    false - no es valido
     *    
     * Un nombre es valido si solo contiene caracteres alfanumericos,_ o espacio en blanco
     */
    public boolean esValidoElCampo() {
        if ( jList1.getSelectedIndex()>10)
            return true;
        return false;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        if (esValidoElCampo()) {
            instalar.borrarCampo(jList1.getSelectedIndex());
            jList1.remove(jList1.getSelectedIndex());
            jLabel1.setText("Puedes añadir "+(4-instalar.getNumcamposOp())+" campos más");
            if (instalar.getNumcamposOp()==4)
                jButton4.setEnabled(false);
            else jButton4.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
        
        if(!textoNC.getText().equals("")) {
            if (validarNombre(textoNC.getText())) {
                
                instalar.addCampo(instalar.nombreCampoABD(textoNC.getText()),(String)tipoDato.getSelectedItem(),jList1.getItemCount());
                
                actualizarListado();
            } else JOptionPane.showMessageDialog(this.getParent(),"Error en el nombre del campo: \nEl nombre del campo debe solo contener caracteres alfanumericos y espacios en blanco");
        }
        jLabel1.setText("Puedes añadir "+(4-instalar.getNumcamposOp())+" campos más");
        if (instalar.getNumcamposOp()==4)
            jButton4.setEnabled(false);
        textoNC.setText("");
        textoNC.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed
   
    
    /**
     * Actualiza el listado de campos
     */
    public void actualizarListado() {
        jList1.removeAll();
        instalar.ordenar();
        for(int i=0;i<instalar.getNumeroCampos();i++) {
            jList1.add( instalar.nombreCampoAPantalla(((DatoCampo)instalar.getCampo(i)).getNombre()));
        }
    }
    
    /**
     * Nos dice si el caracter pasado es una letra o no
     * @param c caracter a comprobar
     * 
     * @return si es o no una letra
     */
    public boolean esLetra(char c) {
        
        return ( ((c>='a')&&(c<='z'))||((c>='A')&&(c<='Z')));
        
    }
    
    /**
     * Nos dice si el caracter pasado es un numero o no
     * @param c El caracter a comprobar
     * 
     * @return Si es o no un numero
     */
    public boolean esNumero(char c) {
        
        return  ((c>='0')&&(c<='9'));
        
    }
    
    /**
     * Nos dice si el caracter pasado es un  espacio en blanco o no
     * @param c El caracter a comprobar
     * @return Si es o no un espacio en blanco
     */
    public boolean esEspacio(char c) {
        
        return  (c==' ');
        
    }
    
    /**
     * Comprueba si el Nombre es valido
     * @param nombre nombre a validar
     * @return si es o no valido
     */
    public boolean validarNombre(String nombre) {
        
        for (int i=0;i<nombre.length();i++)
            if ( !esLetra(nombre.charAt(i)))
                if (! esNumero(nombre.charAt(i)))
                    if (!esEspacio(nombre.charAt(i)) ) {
            return false;
                    }
        
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private java.awt.List jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textoNC;
    private javax.swing.JComboBox tipoDato;
    // End of variables declaration//GEN-END:variables
    
}
