/*
 * VPaso1.java
 *
 * Created on 3 de febrero de 2006, 9:03
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */

package bgc.asistente;

import bgc.negocio.DatosNegocio;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Ventana del asistente
 * @author Campus-Teleamtika S.L.
 */
public class VPaso1 extends javax.swing.JFrame {
    
    JPanel panel;
    InformacionInstalacion instal;
    /** Creates new form VPaso1 */
    public VPaso1() {
        initComponents();
        instal=new InformacionInstalacion();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        panel=new PanelFondo(instal);
        panel.setSize(491, 146);
        panel.setLocation(20,10);
        this.jLabel2.add(panel);
        validate();
        paso=0;
        this.setSize(560, 350);
        this.setLocation(screenSize.width/2-this.getSize().width/2, screenSize.height/2-this.getSize().height/2);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonSig = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonAnterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asistente Base de datos Hermes");
        setBackground(new java.awt.Color(204, 218, 185));
        setIconImage(new ImageIcon(getClass().getResource("/hermes/imagenes/iconos_barra/icono_barra.png")).getImage());
        jPanel1.setBackground(new java.awt.Color(204, 218, 185));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgc/asistente/imagenes/fondo_instalador.png")));

        botonSig.setBackground(new java.awt.Color(240, 240, 240));
        botonSig.setFont(new java.awt.Font("Arial", 0, 12));
        botonSig.setText("Siguiente");
        botonSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSigActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(240, 240, 240));
        botonCancelar.setFont(new java.awt.Font("Arial", 0, 12));
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAnterior.setBackground(new java.awt.Color(240, 240, 240));
        botonAnterior.setFont(new java.awt.Font("Arial", 0, 12));
        botonAnterior.setText("Anterior");
        botonAnterior.setEnabled(false);
        botonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnteriorActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(botonCancelar)
                        .add(9, 9, 9)
                        .add(botonAnterior)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(botonSig))
                    .add(jLabel2))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(botonSig)
                    .add(botonCancelar)
                    .add(botonAnterior))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
// TODO add your handling code here:
        if( JOptionPane.showConfirmDialog(this.getParent(),"Si cancela el asistente se creara la Base de datos con los valores por defecto.\n ¿Desea salir y cancelar la configuración de la base de datos?","Importante",JOptionPane.OK_CANCEL_OPTION,JOptionPane.ERROR_MESSAGE) ==JOptionPane.OK_OPTION) {
            DatosNegocio datos=new DatosNegocio();
            datos.setCif("");
            datos.setEmail("");
            datos.setNombreComercio("");
            datos.setPrimeraVez(false);
            datos.guardarDatos();
            botonCancelar.setVisible(false);
            botonAnterior.setVisible(false);
            getBotonSig().setText("Finalizar");
            getBotonSig().setEnabled(false);
            cargarPanel(new PanelProgreso(instal),40,10,452, 280);
            paso=4;
            
        }
//            System.exit(0);
        
    }//GEN-LAST:event_botonCancelarActionPerformed
    
    private void botonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnteriorActionPerformed
// TODO add your handling code here:
        switch(paso) {
            case 1:{
                cargarPanel(new PanelFondo(instal),40,10,353, 171);
                paso=0;
                botonAnterior.setEnabled(false);
                
            }break;
            
            case 2:{
                
                cargarPanel(new Panel3(instal),40,10,370, 266);
                paso=1;
                
                
            }break;
            case 3:{
                cargarPanel(new Panel2(instal),40,10,440, 264);
                paso=2;
            }break;
        }
        
        
    }//GEN-LAST:event_botonAnteriorActionPerformed
    
    private void cargarPanel(JPanel p,int posx,int posy,int tamx,int tamy) {
        this.jLabel2.remove(panel);
        panel=p;
        panel.setSize(tamx,tamy);
        panel.setLocation(posx,posy);
        this.jLabel2.add(panel);
        validate();
        repaint();
    }
    
    
    private void botonSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSigActionPerformed
// TODO add your handling code here:
        
        
        switch(paso) {
            case 0:{
                cargarPanel(new Panel3(instal),40,10,370, 266);
                paso=1;
                botonAnterior.setEnabled(true);
                
            }break;
            
            case 1:{
                instal.setNombreNegocio(((Panel3)panel).getNombre() );
                instal.setEmail(((Panel3)panel).getEmail());
                instal.setCif(((Panel3)panel).getCIF());
                DatosNegocio datos=new DatosNegocio();
                datos.setCif(instal.getCif());
                datos.setEmail(instal.getEmail());
                datos.setNombreComercio(instal.getNombreNegocio());
                datos.setPrimeraVez(false);
                datos.guardarDatos();
                cargarPanel(new Panel2(instal),40,10,440, 264);
                paso=2;
                
            }break;
            case 2:{
                cargarPanel(new Panel4(instal),40,10,452, 190);
                paso=3;
            }break;
            case 3:{
                botonCancelar.setVisible(false);
                botonAnterior.setVisible(false);
                getBotonSig().setText("Finalizar");
                getBotonSig().setEnabled(false);
                cargarPanel(new PanelProgreso(instal),40,10,452, 280);
                paso=4;
                
            }break;
            case 4:{
                this.dispose();
            }
            
        }
        
        
        
        
    }//GEN-LAST:event_botonSigActionPerformed
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnterior;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonSig;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    int paso;
    
    /**
     * 
     * @return 
     */
    public javax.swing.JButton getBotonSig() {
        return botonSig;
    }
    
    /**
     * 
     * @return 
     */
    public javax.swing.JPanel getJPanel1() {
        return jPanel1;
    }
}
